import assert from 'node:assert/strict';
import {openStore,clockFrom} from './source/v3ref/store.mjs';
import {rightAt} from './source/v3ref/authz.mjs';
import {grantAdjudicationAuthority,suspendMembership,submitClaim,readClaim,adjudicateClaim} from './source/v3ref/adjudication.mjs';
const results=[];
function test(id,fn){const store=openStore(),clock=clockFrom('2026-09-12T10:00:00.000Z');try{for(const id of ['judge','member','outsider'])store.run('INSERT INTO subject VALUES (?,?)',id,'person');store.run('INSERT INTO book VALUES (?,?)','book','Synthetic');store.run('INSERT INTO membership VALUES (?,?,?,?,NULL)','member','book','user','2026-09-01T00:00:00.000Z');for(const operation of ['suspend','adjudicate'])grantAdjudicationAuthority({store,clock,subjectId:'judge',bookId:'book',operation});fn(store,clock);results.push({id,result:'PASS'});}catch(e){results.push({id,result:'FAIL',message:e.message});}finally{store.close();}}
const claim=(store,clock)=>{submitClaim({store,clock,claimantRef:'ref',bookId:'book',statement:'Please investigate synthetic statement 42.'});return store.get('SELECT id FROM claim').id;};
test('C01-unauthorized-suspension-denied',(store,clock)=>assert.equal(suspendMembership({store,clock,actorSubjectId:'outsider',subjectId:'member',bookId:'book'}).ok,false));
test('C02-read-neutrality',(store,clock)=>{const id=claim(store,clock);assert.deepEqual(readClaim({store,clock,viewerSubjectId:'outsider',claimId:id}),readClaim({store,clock,viewerSubjectId:'outsider',claimId:'missing'}));});
test('C03-claim-does-not-grant-membership',(store,clock)=>{claim(store,clock);assert.equal(rightAt({store,clock,subjectId:'outsider',bookId:'book',opClass:'own_book'}).allowed,false);});
test('F01-successful-suspension-removes-current-access',(store,clock)=>{const args={store,clock,subjectId:'member',bookId:'book',opClass:'own_book'};assert.equal(rightAt(args).allowed,true);assert.equal(suspendMembership({...args,actorSubjectId:'judge'}).suspended,true);assert.equal(rightAt(args).allowed,false,'suspended:true but rightAt.allowed remains true');});
test('F02-adjudication-denial-neutrality',(store,clock)=>{const id=claim(store,clock),args={store,clock,actorSubjectId:'outsider',decision:'review'};assert.deepEqual(adjudicateClaim({...args,claimId:id}),adjudicateClaim({...args,claimId:'missing'}));});
test('F03-authorized-reviewer-can-retrieve-submitted-content',(store,clock)=>{const id=claim(store,clock),r=readClaim({store,clock,viewerSubjectId:'judge',claimId:id});assert.equal(r.ok,true);assert.equal(r.claim.statement,'Please investigate synthetic statement 42.','No statement or resolvable content reference is stored or returned; digest alone is not content');});
test('F04-failed-intake-is-atomic',(store,clock)=>{const wrapper={...store,run(sql,...args){if(sql.includes('INSERT OR IGNORE INTO claim'))throw Error('injected storage failure');return store.run(sql,...args);}};assert.throws(()=>claim(wrapper,clock),/injected/);assert.equal(store.get('SELECT COUNT(*) AS n FROM claim_intake').n,0,'failed submission left intake/quota write committed');});
test('F05-caller-chosen-reference-is-not-a-rate-limit-identity',(store,clock)=>{const accepted=[];for(let i=0;i<4;i++)accepted.push(submitClaim({store,clock,claimantRef:'arbitrary-'+i,bookId:'book',statement:'same caller'}).accepted);assert.equal(accepted.filter(Boolean).length<=3,true,'four submissions accepted by changing an unverified caller-controlled reference');});
console.log(JSON.stringify({scope:'isolated reference functions and SQLite, no HTTP or production claim',results,passed:results.filter(x=>x.result==='PASS').length,failed:results.filter(x=>x.result==='FAIL').length},null,2));process.exitCode=results.some(x=>x.result==='FAIL')?1:0;
