import assert from 'node:assert/strict';
import {openStore,clockFrom} from './source/v3ref/store.mjs';
import {rightAt} from './source/v3ref/authz.mjs';
import {grantAdjudicationAuthority,suspendMembership,submitClaim,readClaim,adjudicateClaim,liftSuspension} from './source/v3ref/adjudication.mjs';
const results=[];
function test(id,fn){const store=openStore(),clock=clockFrom('2026-09-12T10:00:00.000Z');try{for(const id of ['judge','member','outsider'])store.run('INSERT INTO subject VALUES (?,?)',id,'person');store.run('INSERT INTO book VALUES (?,?)','book','Synthetic');store.run('INSERT INTO membership VALUES (?,?,?,?,NULL)','member','book','user','2026-09-01T00:00:00.000Z');for(const operation of ['suspend','adjudicate'])grantAdjudicationAuthority({store,clock,subjectId:'judge',bookId:'book',operation});fn(store,clock);results.push({id,result:'PASS'});}catch(e){results.push({id,result:'FAIL',message:e.message});}finally{store.close();}}
const claim=(store,clock)=>{submitClaim({store,clock,claimantRef:'ref',bookId:'book',statement:'Please investigate synthetic statement 42.'});return store.get('SELECT id FROM claim').id;};
test('C01-suspension-lift-preserves-history',(store,clock)=>{const a={store,clock,actorSubjectId:'judge',subjectId:'member',bookId:'book'};suspendMembership(a);clock.advance(1000);assert.equal(rightAt({...a,opClass:'own_book'}).allowed,false);assert.equal(liftSuspension(a).lifted,true);assert.equal(rightAt({...a,opClass:'own_book'}).allowed,true);assert.equal(store.get('SELECT COUNT(*) AS n FROM membership_suspension').n,1);});
test('C02-corrupt-content-not-disclosed',(store,clock)=>{const id=claim(store,clock);store.run('UPDATE claim_content SET content=? WHERE claim_id=?','corrupt',id);assert.equal(readClaim({store,clock,viewerSubjectId:'judge',claimId:id}).error,'claim_content_integrity_failed');});
test('F01-corrupt-content-cannot-be-resolved',(store,clock)=>{const id=claim(store,clock);store.run('UPDATE claim_content SET content=? WHERE claim_id=?','corrupt',id);assert.equal(readClaim({store,clock,viewerSubjectId:'judge',claimId:id}).ok,false);const r=adjudicateClaim({store,clock,actorSubjectId:'judge',claimId:id,decision:'resolve'});assert.equal(r.ok,false,'read refuses corrupted evidence but decision succeeds');});
test('F02-missing-content-cannot-be-resolved',(store,clock)=>{const id=claim(store,clock);store.run('DELETE FROM claim_content WHERE claim_id=?',id);assert.equal(readClaim({store,clock,viewerSubjectId:'judge',claimId:id}).ok,false);assert.equal(adjudicateClaim({store,clock,actorSubjectId:'judge',claimId:id,decision:'resolve'}).ok,false,'missing evidence still resolves');});
test('F03-distinct-channel-cannot-be-blocked-by-spoofed-ref',(store,clock)=>{for(let i=0;i<3;i++)submitClaim({store,clock,claimantRef:'victim',bookId:'book',statement:'attacker-'+i,intakeContext:{channel_key:'attacker'}});const r=submitClaim({store,clock,claimantRef:'victim',bookId:'book',statement:'legitimate',intakeContext:{channel_key:'independent-victim'}});assert.equal(r.accepted,true,'a separate server channel remains blocked by caller-chosen victim reference');});
console.log(JSON.stringify({results,passed:results.filter(x=>x.result==='PASS').length,failed:results.filter(x=>x.result==='FAIL').length},null,2));process.exitCode=results.some(x=>x.result==='FAIL')?1:0;
