import assert from 'node:assert/strict';
import {openStore,clockFrom} from './source/v3ref/store.mjs';
import {rightAt} from './source/v3ref/authz.mjs';
import {issueBan,imposeBan} from './source/v3ref/ban.mjs';
import {adjudicationRightAt,grantAdjudicationAuthority,submitClaim,readClaim} from './source/v3ref/adjudication.mjs';
const results=[];
function test(id,fn){const store=openStore(),clock=clockFrom('2026-09-14T06:00:00.000Z');try{for(const s of ['judge','member','outsider'])store.run('INSERT INTO subject VALUES (?,?)',s,'person');for(const b of ['a','b']){store.run('INSERT INTO book VALUES (?,?)',b,b);store.run('INSERT INTO membership VALUES (?,?,?,?,NULL)','member',b,'user',clock.now());}for(const operation of ['alter_right','adjudicate'])grantAdjudicationAuthority({store,clock,subjectId:'judge',bookId:'a',operation});const raw=(subject,cause,kind,target)=>store.run('INSERT INTO subject_ban(subject_id,cause,kind,target_ref,actor_subject_id,banned_at) VALUES(?,?,?,?,?,?)',subject,cause,kind,target,'outsider',clock.now());const args={store,clock,subjectId:'member',actorSubjectId:'judge',bookId:'a'};const right=b=>rightAt({store,clock,subjectId:'member',bookId:b,opClass:'own_book'});fn({store,clock,raw,args,right});results.push({id,pass:true});}catch(e){results.push({id,pass:false,error:e.message});}finally{store.close();}}
test('C01-authorized-book-ban-and-independent-book',({args,right})=>{assert(right('a').allowed&&right('b').allowed);assert(issueBan({...args,cause:'left_company',targetRef:'a'}).ok);assert(!right('a').allowed&&right('b').allowed);});
test('C02-no-authority-and-outside-book-refused',({args,store})=>{assert.equal(issueBan({...args,actorSubjectId:'outsider',cause:'left_company',targetRef:'a'}).ok,false);assert.equal(issueBan({...args,cause:'left_company',targetRef:'b'}).ok,false);assert.equal(store.get('SELECT count(*) n FROM subject_ban').n,0);});
test('F01-banned-issuer-cannot-issue-ban',({store,clock,raw,args})=>{raw('judge','left_company','book','a');const right=adjudicationRightAt({store,clock,subjectId:'judge',bookId:'a',operation:'alter_right'});assert.equal(right.allowed,false);const r=issueBan({...args,cause:'left_company',targetRef:'a'});assert.equal(r.ok,false,JSON.stringify({issuer_right:right,issued:r}));});
test('F02-book-authority-does-not-ban-independent-book-operation',({args,right})=>{assert(right('b').allowed);const r=issueBan({...args,cause:'operation_misuse',targetRef:'own_book'});assert(r.ok);assert.equal(right('a').allowed,false);assert.equal(right('b').allowed,true,JSON.stringify({issued:r,independent_book:right('b')}));});
test('F03-exported-writer-cannot-bypass-scope',({args,right})=>{assert.equal(issueBan({...args,cause:'left_company',targetRef:'b'}).ok,false);const r=imposeBan({...args,cause:'left_company',targetRef:'b'});assert.equal(r.ok,false,JSON.stringify({issued:r,independent_book:right('b')}));});
test('F04-unknown-stored-cause-not-a-permit',({raw,right})=>{raw('member','unknown-imported-cause','book','b');const r=right('a');assert.equal(r.allowed,false,JSON.stringify(r));});
test('F05-good-credential-reaches-claim-read',({store,clock,raw})=>{submitClaim({store,clock,claimantRef:'synthetic',bookId:'a',statement:'Synthetic claim'});const claimId=store.get('SELECT id FROM claim').id;const call=credentials=>readClaim({store,clock,viewerSubjectId:'judge',claimId,credentials});assert.equal(call().ok,true);raw('judge','credential_compromised','credential','old');assert.equal(adjudicationRightAt({store,clock,subjectId:'judge',bookId:'a',operation:'adjudicate',credentials:{credentialId:'new'}}).allowed,true);const r=call({credentialId:'new'});assert.equal(r.ok,true,JSON.stringify(r));});
console.log(JSON.stringify({scope:'pinned reference; real isolated SQLite; issueBan public entry and exported writer, no live endpoints',results,passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length},null,2));process.exitCode=results.some(x=>!x.pass)?1:0;
