import assert from 'node:assert/strict';
import {openStore,clockFrom} from './source/v3ref/store.mjs';
import {rightAt} from './source/v3ref/authz.mjs';
import {issueBan,operationScopeRef} from './source/v3ref/ban.mjs';
import {grantAdjudicationAuthority,suspendMembership,liftSuspension} from './source/v3ref/adjudication.mjs';
import {submitCommand,readCommandResult} from './source/v3ref/command.mjs';
import {banMatrix} from './source/v3ref/banMatrix.mjs';
const results=[];
const T='2026-09-14T08:00:00.000Z';
function test(id,fn){const store=openStore(),clock=clockFrom(T);try{for(const s of ['judge','member'])store.run('INSERT INTO subject VALUES (?,?)',s,'person');for(const b of ['a','b']){store.run('INSERT INTO book VALUES (?,?)',b,b);store.run('INSERT INTO membership VALUES (?,?,?,?,NULL)','member',b,'user',T);for(const operation of ['suspend','alter_right'])grantAdjudicationAuthority({store,clock,subjectId:'judge',bookId:b,operation});}const raw=(subject,kind,cause,target)=>store.run('INSERT INTO subject_ban(subject_id,kind,cause,target_ref,actor_subject_id,banned_at) VALUES(?,?,?,?,?,?)',subject,kind,cause,target,'judge',T);fn({store,clock,raw});results.push({id,pass:true});}catch(e){results.push({id,pass:false,error:e.message});}finally{store.close();}}
const plans=[['book','left_company','a',null],['operation','operation_misuse',operationScopeRef('a','suspend'),null],['subject','court_order_subject',null,null],['credential','credential_compromised','old','credentialId'],['session','session_hijack_suspected','old','sessionId'],['legal_basis','mandate_withdrawn','old','basisId'],['data_scope','data_scope_withdrawn','old','dataScope']];
for(const path of ['suspend','lift'])for(const [kind,cause,target,axis]of plans)for(const mode of axis?['matching','other','absent']:(kind==='subject'?['matching']:['matching','other']))test(`M-${path}-${kind}-${mode}`,({store,clock,raw})=>{const bookId=!axis&&mode==='other'?'b':'a';if(path==='lift')store.run('INSERT INTO membership_suspension(subject_id,book_id,actor_subject_id,suspended_at) VALUES(?,?,?,?)','member',bookId,'judge',T);raw('judge',kind,cause,target);const credentials=axis&&mode!=='absent'?{[axis]:mode==='matching'?'old':'new'}:undefined;const before=JSON.stringify(store.all('SELECT * FROM membership_suspension ORDER BY id'));const r=(path==='suspend'?suspendMembership:liftSuspension)({store,clock,actorSubjectId:'judge',subjectId:'member',bookId,credentials});const expected=mode==='other';assert.equal(r.ok,expected,JSON.stringify(r));if(!expected)assert.equal(JSON.stringify(store.all('SELECT * FROM membership_suspension ORDER BY id')),before);else assert.equal(rightAt({store,clock,subjectId:'member',bookId,opClass:'own_book'}).allowed,path==='lift');});
for(const path of ['issue','suspend','lift'])test(`F01-${path}-authority-expired-at-write`,({store,clock})=>{if(path==='lift')assert(suspendMembership({store,clock,actorSubjectId:'judge',subjectId:'member',bookId:'a'}).ok);store.run('UPDATE adjudication_authority SET revoked_at=? WHERE subject_id=?','2026-09-14T08:00:01.000Z','judge');let calls=0;const advancing={now:()=>++calls===1?T:'2026-09-14T08:00:02.000Z'};const a={store,clock:advancing,actorSubjectId:'judge',subjectId:'member',bookId:'a'};const r=path==='issue'?issueBan({...a,cause:'left_company',targetRef:'a'}):(path==='suspend'?suspendMembership(a):liftSuspension(a));assert.equal(r.ok,false,JSON.stringify({calls,result:r}));});
test('F02-data-scope-context-does-not-filter-price-result',({store,clock,raw})=>{assert(submitCommand({store,clock,actor:'member',bookId:'a',idemKey:'price',type:'stock.receipt',typeVersion:'1',declared:{qty:1},resolve:()=>({qty:1,unit_price:12345})}).ok);raw('member','data_scope','data_scope_withdrawn','arak');const args={store,clock,requester:'member',bookId:'a',actor:'member',idemKey:'price'};assert.equal(readCommandResult({...args,credentials:{dataScope:'arak'}}).ok,false);const r=readCommandResult({...args,credentials:{dataScope:'keszlet'}});assert(!r.ok||!Object.hasOwn(r.result||{},'unit_price'),JSON.stringify(r));});
test('F03-malformed-operation-scope-is-undecidable',({store,clock,raw})=>{raw('member','operation','operation_misuse','\u0001own_book');const r=rightAt({store,clock,subjectId:'member',bookId:'a',opClass:'own_book'});assert.equal(r.allowed,false,JSON.stringify(r));});
const matrix=banMatrix();const count={};for(const c of matrix.cells)count[c.actual]=(count[c.actual]||0)+1;
const keys=new Set(matrix.cells.filter(c=>c.actual!=='n/a').map(c=>JSON.stringify([c.kind,c.path,c.book_id,c.op_class,c.context])));
console.log(JSON.stringify({scope:'actual reference entry points, real isolated SQLite; contextual kinds assume supplied trusted context; disclosure and expiry probes expose integration limits',results,passed:results.filter(x=>x.pass).length,failed:results.filter(x=>!x.pass).length,matrix:{rows:matrix.cells.length,counts:count,uniqueExecutedInputs:keys.size,mismatches:matrix.mismatches.length}},null,2));process.exitCode=results.some(x=>!x.pass)?1:0;
