import assert from 'node:assert/strict';
import {openStore,clockFrom} from './source/v3ref/store.mjs';
import {rightAt,revokeMembership} from './source/v3ref/authz.mjs';
import {effectuate} from './source/v3ref/authority.mjs';
import {grantAdjudicationAuthority,submitClaim,adjudicateClaim} from './source/v3ref/adjudication.mjs';
import {submitCommand,readCommandResult} from './source/v3ref/command.mjs';
const T='2026-09-14T08:00:00.000Z',END='2026-09-14T08:00:01.000Z',LATE='2026-09-14T08:00:02.000Z';const cases=[];
function test(id,fn){const store=openStore(),clock=clockFrom(T);try{for(const s of ['judge','member'])store.run('INSERT INTO subject VALUES (?,?)',s,'person');store.run('INSERT INTO book VALUES (?,?)','a','A');store.run('INSERT INTO membership VALUES (?,?,?,?,NULL)','member','a','user',T);for(const operation of ['suspend','alter_right','adjudicate'])grantAdjudicationAuthority({store,clock,subjectId:'judge',bookId:'a',operation});const ban=(kind,cause,target)=>store.run('INSERT INTO subject_ban(subject_id,kind,cause,target_ref,actor_subject_id,banned_at) VALUES(?,?,?,?,?,?)','member',kind,cause,target,'judge',T);fn({store,clock,ban});cases.push({id,pass:true});}catch(e){cases.push({id,pass:false,error:e.message});}finally{store.close();}}
for(const [id,result,expected] of [['P01-flat-quantity',{qty:1},true],['P02-flat-price',{qty:1,unit_price:12345},false],['F01-nested-price',{lines:[{qty:1,unit_price:12345}]},false],['F01-object-in-qty',{qty:{unit_price:12345}},false],['P03-unknown-top-field',{private_price:12345},false]])test(id,({store,clock,ban})=>{ban('data_scope','data_scope_withdrawn','arak');const s=submitCommand({store,clock,actor:'member',bookId:'a',idemKey:'x',type:'stock.receipt',typeVersion:'1',declared:{qty:1},resolve:()=>result,credentials:{dataScope:'keszlet'}});const r=s.ok?readCommandResult({store,clock,requester:'member',actor:'member',bookId:'a',idemKey:'x',credentials:{dataScope:'keszlet'}}):s;assert.equal(r.ok,expected,JSON.stringify({submit:s,read:r}));});
for(const mode of ['before','after','cross'])test(`P04-revoke-${mode}`,({store,clock})=>{store.run('UPDATE adjudication_authority SET revoked_at=?',END);let n=0;const c={now:()=>mode==='before'?T:mode==='after'?LATE:++n===1?T:LATE};const r=revokeMembership({store,clock:c,actorSubjectId:'judge',subjectId:'member',bookId:'a'});assert.equal(r.ok,mode==='before',JSON.stringify(r));if(!r.ok)assert.equal(store.get('SELECT revoked_at FROM membership').revoked_at,null);});
for(const mode of ['before','after','cross'])test(`P06-adjudicate-${mode}`,({store,clock})=>{submitClaim({store,clock,claimantRef:'synthetic',bookId:'a',statement:'test',intakeContext:{channel:'test',source:'synthetic'}});const row=store.get('SELECT * FROM claim');assert(row);store.run('UPDATE adjudication_authority SET revoked_at=?',END);let n=0;const c={now:()=>mode==='before'?T:mode==='after'?LATE:++n===1?T:LATE};const r=adjudicateClaim({store,clock:c,actorSubjectId:'judge',claimId:row.id,decision:'resolve'});assert.equal(r.ok,mode==='before',JSON.stringify(r));assert.equal(store.get('SELECT state FROM claim').state,mode==='before'?'resolved':'received');});
for(const mode of ['before','after'])test(`P07-command-${mode}`,({store})=>{store.run('UPDATE membership SET revoked_at=?',END);const r=submitCommand({store,clock:clockFrom(mode==='before'?T:LATE),actor:'member',bookId:'a',idemKey:'time-control',type:'stock.receipt',typeVersion:'1',declared:{qty:1},resolve:()=>({qty:1})});assert.equal(r.ok,mode==='before');assert.equal(store.all('SELECT * FROM command').length,mode==='before'?1:0);});
test('P05-nested-effect-rolls-back',({store,clock})=>{assert.throws(()=>effectuate({store,clock,subjectId:'judge',bookId:'a',operation:'alter_right'},()=>{store.run('UPDATE membership SET role=?','admin');revokeMembership({store,clock,actorSubjectId:'judge',subjectId:'member',bookId:'a'});}),/beágyazott/);assert.equal(store.get('SELECT role FROM membership').role,'user');});
test('F02-command-time-splits-at-finalization',({store})=>{store.run('UPDATE membership SET revoked_at=?',END);let n=0;const clock={now:()=>++n<=9?T:LATE};const r=submitCommand({store,clock,actor:'member',bookId:'a',idemKey:'late',type:'stock.receipt',typeVersion:'1',declared:{qty:1},resolve:()=>({qty:1})});const row=store.get('SELECT * FROM command');assert(!row||rightAt({store,clock:clockFrom(row.finalized_at),subjectId:'member',bookId:'a',opClass:'own_book'}).allowed,JSON.stringify({calls:n,result:r,finalized_at:row?.finalized_at,revoked_at:END}));});
for(const mode of ['matching','other','absent'])test(`F03-revoke-credential-${mode}`,({store,clock})=>{store.run('INSERT INTO subject_ban(subject_id,kind,cause,target_ref,actor_subject_id,banned_at) VALUES(?,?,?,?,?,?)','judge','credential','credential_compromised','old','judge',T);const credentials=mode==='absent'?undefined:{credentialId:mode==='matching'?'old':'new'};const r=revokeMembership({store,clock,actorSubjectId:'judge',subjectId:'member',bookId:'a',credentials});assert.equal(r.ok,mode==='other',JSON.stringify(r));});
console.log(JSON.stringify({commit:'8dced6f444aff777d5842a050101eedefdcdeec1',cases,passed:cases.filter(x=>x.pass).length,failed:cases.filter(x=>!x.pass).length},null,2));process.exitCode=cases.some(x=>!x.pass)?1:0;
