import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';
const root=import.meta.dirname,cases=[];
const plans=[['P01-genuine',()=>{},true],['P02-missing-unit',(d,us)=>fs.rmSync(us[0]),false],['P03-foreign-digest',(d,us)=>edit(us[0],u=>u.base_digest='sha256:foreign'),false],['P04-duplicate-unit',(d,us)=>fs.copyFileSync(us[0],path.join(d,'v3ref/units/unit-99-of-99.json')),false],['F01-empty-results',(d,us)=>us.forEach(f=>edit(f,u=>u.mutation_results=[])),false],['F01-contradictory-verdict',(d,us)=>us.forEach(f=>edit(f,u=>u.mutation_results.forEach(r=>{r.verdict='SURVIVED';r.probe_status='PASS';r.failed_assertions=[];}))),false],['F02-empty-required',(d,us)=>us.forEach(f=>edit(f,u=>{u.norm_required.clauses=[];u.norm_chain=[];})),false],['F03-wrong-contract',(d,us)=>us.forEach(f=>edit(f,u=>u.run_contract='RUN-FOREIGN')),false]];
function edit(f,fn){const u=JSON.parse(fs.readFileSync(f));fn(u);fs.writeFileSync(f,JSON.stringify(u));}
for(const[id,change,expected]of plans){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'r81-merge-'));try{fs.cpSync(path.join(root,'source'),dir,{recursive:true});fs.rmSync(path.join(dir,'v3ref/units'),{recursive:true,force:true});fs.cpSync(path.join(root,'evidence/genuine-units'),path.join(dir,'v3ref/units'),{recursive:true});const us=fs.readdirSync(path.join(dir,'v3ref/units')).map(f=>path.join(dir,'v3ref/units',f));change(dir,us);const r=spawnSync(process.execPath,[path.join(dir,'v3ref/mutate.mjs'),'--merge'],{cwd:dir,encoding:'utf8',timeout:15000,maxBuffer:2e6});const o=JSON.parse(fs.readFileSync(path.join(dir,'v3ref/v3ref-mutation-result.json')));const accepted=r.status===0&&o.run_state==='complete'&&o.clean===true;cases.push({id,pass:accepted===expected,exit:r.status,run_state:o.run_state,clean:o.clean,counts:o.mutations,result_count:o.mutation_results.length,required:o.norm_evidence?.required,why:o.why});}catch(e){cases.push({id,pass:false,harness_error:e.message});}finally{fs.rmSync(dir,{recursive:true,force:true});}}
fs.writeFileSync(path.join(root,'evidence/merge-challenge.json'),JSON.stringify({cases,passed:cases.filter(c=>c.pass).length,failed:cases.filter(c=>!c.pass).length},null,2));console.log(cases.map(({id,pass,exit,result_count})=>({id,pass,exit,result_count})));

process.exitCode=cases.some(x=>!x.pass)?1:0;

