import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';import {PROGRAMS} from './source/v3ref/external-checks/case-manifest.mjs';
const root=import.meta.dirname,cases=[];
for(const mode of ['all-green','original-real-failure','original-and-sub-failure']){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'r83-runner-'));try{fs.cpSync(path.join(root,'source'),dir,{recursive:true});
for(const p of PROGRAMS){const fail=p.id==='r57'&&mode!=='all-green'||p.id==='r57a'&&mode==='original-and-sub-failure';const rows=p.cases.map((id,i)=>({id,pass:!(fail&&i===0),...(fail&&i===0?{reason:'synthetic assertion failure; NOT a timeout'}:{})}));
const code=`import fs from 'node:fs';import path from 'node:path';const root=import.meta.dirname;const pin=JSON.parse(fs.readFileSync(path.join(root,'source-manifest.json'))).commit;const cases=${JSON.stringify(rows)};fs.mkdirSync(path.join(root,'evidence'),{recursive:true});fs.writeFileSync(path.join(root,'evidence',${JSON.stringify(p.evidence)}),JSON.stringify({[${JSON.stringify(p.evidence_pin_field)}]:pin,cases}));console.log(JSON.stringify(cases));`;
fs.writeFileSync(path.join(dir,'v3ref/external-checks',p.file),code);}
const out=path.join(dir,'out');const r=spawnSync(process.execPath,[path.join(dir,'v3ref/external-checks/run-all.mjs'),'--out',out],{cwd:dir,encoding:'utf8',timeout:30000,maxBuffer:4e6});const o=JSON.parse(fs.readFileSync(path.join(out,'external-checks-result.json')));const orig=o.programs.find(x=>x.id==='r57');cases.push({mode,pass:(r.status===0)===(mode==='all-green'),exit:r.status,verdict:o.verdict,original:{ok:orig.ok,failed:orig.failed,error:orig.error,env_skipped:orig.env_skipped,problems:orig.problems}});
}catch(e){cases.push({mode,pass:false,harness_error:e.message});}finally{fs.rmSync(dir,{recursive:true,force:true});}}
fs.writeFileSync(path.join(root,'evidence/runner-r83.json'),JSON.stringify({scope:'real runner with synthetic program outputs; no product behavior claim',cases},null,2));console.log(cases);process.exitCode=cases.some(x=>!x.pass)?1:0;
