import fs from 'node:fs';
import {openStore,clockFrom} from './source/v3ref/store.mjs';
import {grantMembership,membershipAsOf} from './source/v3ref/bitemporal.mjs';
import {recordAuthorityBasis} from './source/v3ref/authorityBasis.mjs';
import {grantAdjudicationAuthority,adjudicationRightAt} from './source/v3ref/adjudication.mjs';
const JAN='2026-01-01T00:00:00.000Z',MAR='2026-03-01T00:00:00.000Z',JUN='2026-06-01T00:00:00.000Z',cases=[];
function test(id,fn){const store=openStore();try{for(const s of ['issuer','member'])store.run('INSERT INTO subject VALUES (?,?)',s,'person');for(const b of ['A','B'])store.run('INSERT INTO book VALUES (?,?)',b,b);cases.push({id,...fn(store)});}catch(e){cases.push({id,pass:false,harness_error:e.message});}finally{store.close();}}
function basis(store){return recordAuthorityBasis({store,basisId:'decision-A',bookId:'A',issuerSubject:'issuer',effectiveAt:JAN,recordedAt:JAN,allowedOperations:['adjudicate'],evidenceRef:'doc:decision-A'});}
test('P01-same-book-basis',store=>{basis(store);grantAdjudicationAuthority({store,subjectId:'member',bookId:'A',operation:'adjudicate',clock:clockFrom(MAR),basisId:'decision-A'});const r=adjudicationRightAt({store,subjectId:'member',bookId:'A',operation:'adjudicate',clock:clockFrom(MAR)});return{pass:r.allowed===true,result:r};});
test('F01-foreign-book-basis',store=>{basis(store);let error=null;try{grantAdjudicationAuthority({store,subjectId:'member',bookId:'B',operation:'adjudicate',clock:clockFrom(MAR),basisId:'decision-A'});}catch(e){error=e.message;}const rows=store.all('SELECT * FROM adjudication_authority');const r=adjudicationRightAt({store,subjectId:'member',bookId:'B',operation:'adjudicate',clock:clockFrom(MAR)});return{pass:rows.length===0&&r.allowed===false,error,rows,result:r};});
test('P02-successful-grant-is-paired',store=>{const r=grantMembership({store,subjectId:'member',bookId:'A',role:'user',at:JUN});return{pass:r.ok===true&&store.all('SELECT * FROM membership_grant').length===1&&store.all('SELECT * FROM membership').length===1,result:r};});
test('F02-rejected-grant-leaves-no-event',store=>{grantMembership({store,subjectId:'member',bookId:'A',role:'user',at:JUN});const query={store,subjectId:'member',bookId:'A',validAt:MAR,knownAt:MAR};const before=membershipAsOf(query);let error=null,result=null;try{result=grantMembership({store,subjectId:'member',bookId:'A',role:'user',at:JAN});}catch(e){error=e.message;}const after=membershipAsOf(query),events=store.all('SELECT * FROM membership_grant');return{pass:(!!error||result?.ok===false)&&events.length===1&&before.effective===false&&after.effective===false,error,result,before,after,event_count:events.length};});
test('P03-outer-transaction-rolls-back',store=>{grantMembership({store,subjectId:'member',bookId:'A',role:'user',at:JUN});let rejected=false;try{const r=store.tx(()=>grantMembership({store,subjectId:'member',bookId:'A',role:'user',at:JAN}));rejected=r?.ok===false;}catch{rejected=true;}const events=store.all('SELECT * FROM membership_grant'),r=membershipAsOf({store,subjectId:'member',bookId:'A',validAt:MAR,knownAt:MAR});return{pass:rejected&&events.length===1&&!r.effective,event_count:events.length,result:r};});
fs.writeFileSync(new URL('./evidence/core-r87.json',import.meta.url),JSON.stringify({cases},null,2));console.log(JSON.stringify(cases,null,2));process.exitCode=cases.some(x=>!x.pass)?1:0;