'use strict';

// Valach System — A KUKA-TANULSÁGOK ŐR-OTTHONA (GHM-01).
//
// MIÉRT LÉTEZIK EZ A FÁJL. A KUKA-regiszter 89 tanulsága ÁTJÖTT a V2-ből, mert a tanulság nem
// verzió-függő. A hozzájuk tartozó GÉPI JELEK viszont a V2 fájljaira mutatnak (`src/…`), ami itt
// nem létezik. Ha ezt elhallgatnánk, két rossz dolog közül az egyik történne:
//   · a tiltó-jel némán ÁTMENNE (nincs mit szkennelni ⇒ nincs találat ⇒ "zöld"), tehát a védelem
//     látszana meglévőnek, holott nincs — pontosan a KUKA-051 és a KUKA-041 hibája;
//   · vagy 85 jel PIROSAN állna az első naptól, és a battéria elveszítené a jelentését.
//
// Ezért MINDEN bejegyzésnek KIMONDOTT otthona van, és a `verify:kuka` a listát KIÍRJA:
//   'v3'   — a jel cél-fájljai ITT vannak, tehát a jel LEFUT (valódi védelem)
//   'vs'   — a jel a V2 repóban (`valach-family/vs`) él; itt NEM fut, a tanulság viszont érvényes
//   'none' — a bejegyzésnek nincs gépi jele, és ezt maga a bejegyzés mondja ki (guard_note)
//
// A 'vs' szám PADLÓ, nem cél: CSÖKKENHET (ahogy a V3 megépíti a saját őrét), NŐNI NEM SZABAD.
// Ez a fájl SZÁRMAZTATOTT állítás, amit a verifier VISSZAMÉR: ha egy 'v3'-nak jelölt bejegyzés
// cél-fájlja hiányzik, vagy egy 'vs'-nek jelölt jel valójában lefuttatható volna, az PIROS.
//
// PURE + INERT: nincs DB, nincs hálózat, nincs titok. Csak adat.

const GUARD_HOME_CONTRACT_ID = 'GHM-01';

// A V2-ben honos jelek MAI száma. Ez a valóság rögzítése, nem cél — lásd fent.
// 2026-09-11 (D-VS-678): 83 → 84. NEM elmaradt átköltöztetés: a KUKA-106 a BOARD indulási útjáról
// szól, a board pedig a V2 repóban él — a jele ott FUT (verify:lanes LAN07), tehát ide nem hozható.
// 2026-09-12 (D-VS-680): 85 → 86. UGYANEZ AZ INDOK, nem új engedmény: a KUKA-112 a board
// bizonyíték-kapujáról szól (a nulla eset nem bizonyíték), a kapu és a jele (verify:matrix-liveness
// MTX06 + a board test:units) a V2 repóban FUT — ide nem hozható, mert a V3-nak nincs boardja.
// A plafon emelése CSAK ilyenkor szabályos: ha az új jel HELYE valóban a V2, nem pedig elmaradt
// átköltöztetés. Az e körben született másik két tanulság (KUKA-111 · KUKA-113) a V3-ban fut.
// 2026-09-12 (R63, D-VS-686): 86 → 90. UGYANAZ AZ INDOK, nem új engedmény: mind a NÉGY új
// tanulság a BOARD bizonyíték-befogadásáról szól (közös szerződés · alkalmazhatóság-alap ·
// a megkerülő út · az arány mint teljesség-mérce), és mind a négy jele a V2 repóban FUT
// (verify:matrix-profiles MPF03/08–13 + a board test:units). A V3-ban nincs board, tehát a
// jelek ide nem hozhatók — a plafon emelése CSAK ilyenkor szabályos.
// 2026-09-12 (R65, D-VS-689): 90 → 92. UGYANAZ AZ INDOK, harmadszor kimondva, mert az ismétlődő
// engedmény a legkönnyebben szokássá váló dolog: mindkét új tanulság a BOARD bizonyíték-útjáról
// szól (a hitelesített szereplő · a fájl ≠ teszteset egység), és mindkettő jele a V2 repóban FUT
// (verify:matrix-profiles MPF10/15/17 + a board test:units). A V3-nak nincs boardja, tehát a jelek
// ide nem hozhatók. AMI VISZONT NEM ENGEDMÉNY: az e körben született MAG-munka (REV-N3a/b/c) jelei
// ITT futnak — verify:v3ref, a P-REV-authority és P-REV-claim-read próbákkal, M50–M55 mutációval.
const VS_HOMED_CEILING = 92;

const GUARD_HOME = Object.freeze({
  'KUKA-275': Object.freeze({ home: 'v3', note: 'a jel cél-fájljai ITT vannak (v3ref/adjudication.mjs · v3ref/authorityHistory.mjs · v3ref/store.mjs) — a jel FUT: pozitív minta a generáció ZÁRÁSÁRA a felülírás előtt, a napló-beli megvonás olvasására, a zárás-tény TÁROLT mezőjére, és arra, hogy a zárás ténye nélkül NINCS néma történeti igen; a viselkedés tanúja a findings_r134 G szakasz (g1)–(g13) a (g12) NEGATÍV kontrollal' }),
  'KUKA-274': Object.freeze({ home: 'v3', note: 'a jel cél-fájlja ITT van (v3ref/external-checks/case-manifest.mjs) — a jel FUT: pozitív minta a KIVEZETETT bővítés deklarációjára (`retired_adaptation`) és a NEVEZETT nyitott maradékra (`open_named`). KIMONDVA, miért nincs tiltó-minta a visszacsúszásra: a `n *= 2` alak önmagában nem hibás — a repó `--units-auto`-ja JOGOSAN használja ugyanezt, ahol nincs program-szintű türelem-korlát; a hiba a HELY volt, nem a minta (KUKA-092)' }),
  'KUKA-273': Object.freeze({ home: 'v3', note: 'a jel cél-fájljai ITT vannak (v3ref/authorityHistory.mjs · v3ref/authority.mjs) — a jel FUT: pozitív minta a generáció-hatókörre (az ÉLŐ generációnál a VETÜLET sora az operatív) és a napló↔vetület divergencia nevezett zárására; a viselkedés MÉRT tanúja a mag-battéria P-ORG-adjudication-basis-limit próbája (a három nyers verzió-alak), ami a visszacsúszásra ezen a körön BIZONYÍTOTTAN pirosra váltott' }),
  'KUKA-272': Object.freeze({ home: 'v3', note: 'a jel cél-fájljai ITT vannak (v3ref/basisLimit.mjs · v3ref/authorityBasis.mjs · v3ref/delegation.mjs · v3ref/store.mjs) — a jel FUT: pozitív minta az eredet-kapura MINDKÉT úton (beváltás és bírálat), a per-generáció eredet-feloldóra, az eredet KÉPZŐ-oldali rögzítésére és a TÁROLT oszlopra; a viselkedés tanúja a findings_r134 (b7b)–(b7f), ami a javítás ELŐTT MÉRVE piros volt' }),
  'KUKA-271': Object.freeze({ home: 'v3', note: 'a jel cél-fájljai ITT vannak (v3ref/authority.mjs · v3ref/authorityHistory.mjs) — a jel FUT: pozitív minta arra, hogy a hatáskör-értékelő a TÖRTÉNETI feloldót hívja, hogy a kiválasztás MINDKÉT tengelyen mér (hatály ÉS tudás), és hogy a napló nélküli sor KIMONDOTT ág; a viselkedés tanúja a findings_r134 (b5b)–(b5f), ami a javítás ELŐTT MÉRVE piros volt' }),
  'KUKA-270': Object.freeze({ home: 'v3', note: 'a jel cél-fájljai ITT vannak (tools/vs_verify_kuka.mjs · contracts/retiredPatternRegistry.js) — a jel FUT: a KUK01 megköveteli, hogy MINTÁT csak a futtatott kulcsok (positive · forbidden) hordozzanak, és tiltó-minta áll a `never:` kulcs visszatérésére' }),
  'KUKA-269': Object.freeze({ home: 'v3', note: 'a jel cél-fájljai ITT vannak (v3app/findings_r132.mjs · v3ref/delegation.mjs) — a jel FUT: a helyesbített lépés az ISMÉTLÉST méri, tiltó-minta a régi, hiányt sikernek nevező lépés-névre; a viselkedés tanúja a P-ORG-reentry-gates (d) és az M326/M327 rontás' }),
  'KUKA-268': Object.freeze({ home: 'v3', note: 'a jel cél-fájlja ITT van (v3ref/authority.mjs) — a jel FUT: a két KIMONDOTT nem-kötési eset pozitív mintája és tiltó-minta a kötés sorrendjére; a viselkedés tanúja a három tiltás-próba zöldje vetített tagsági soron' }),
  'KUKA-267': Object.freeze({ home: 'v3', note: 'a jel cél-fájljai ITT vannak (v3ref/reentryGate.mjs · v3ref/bitemporal.mjs · v3ref/delegation.mjs · v3ref/invite.mjs) — a jel FUT: a kör ESEMÉNY-AZONOSÍTÓS feloldója pozitív mintaként, és tiltó-minta a némán hamis `circle.circle_id` alakra; a viselkedés tanúja a findings_r134 (a8)/(a9)' }),
  'KUKA-266': Object.freeze({ home: 'v3', note: 'a jel cél-fájlja ITT van (v3ref/bitemporal.mjs) — a jel FUT: egy pozitív minta (a döntés bemenete a saját írás ELŐTT olvasott állapot) és egy tiltó-minta (a mérés NEM kerülhet az esemény-beszúrás utánra); a viselkedés tanúja a P-ORG-reentry, amit az M322/M323 rontás bizonyítottan megbuktat' }),
  'KUKA-265': Object.freeze({ home: 'v3', note: 'a jel cél-fájlja ITT van (v3app/public/app.js) — a jel FUT: a nyugta a teljes oldalt újraépítő lekérés UTÁN íródik ki; a DOM-tanú a tests/e2e/v3app-r132.spec.mjs (R132-B1)' }),
  'KUKA-264': Object.freeze({ home: 'v3', note: 'a jel cél-fájlja ITT van (v3app/public/app.js) — a jel FUT: két pozitív minta (a fül-váltás ÉS a lista-tartalom megérkezése is újraértékeli a futó útmutatót); a tanú a tests/e2e/v3app-r93.spec.mjs, ami MIND A TIZENEGY útmutatót végig járja' }),
  'KUKA-263': Object.freeze({ home: 'v3', note: 'a határ-mérés fixture-e és a próbaoldali DOM-figyelő ITT él (tests/e2e/v3app-r127.spec.mjs) — a jel a verify:kuka két pozitív mintája és két tiltó-mintája, valamint az R127-E6 konkrét állításai (DOM-változás > 0, majd mért helyreállás)' }),
  'KUKA-262': Object.freeze({ home: 'v3', note: 'a háromjeles átadás-bizonyítás és a NEGATÍV KONTROLL ITT él (tests/e2e/v3app-r127.spec.mjs) — a jel a verify:kuka három pozitív mintája (benne a fulfill → deliveredAt SORRENDJE) és az R127-N1, ami a kiszolgált /app.js nemzedék-kapujának kikapcsolásával bukásra viszi ugyanazt az állítást' }),
  'KUKA-113': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-111': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-110': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-109': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-108': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-107': Object.freeze({ home: 'vs', note: 'a board a V2 repoban el - a BDR jel OTT fut' }),
  'KUKA-106': Object.freeze({ home: 'vs', note: 'a board a V2 repóban él — a LAN07 jel OTT fut' }),
  'KUKA-105': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-104': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-103': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-102': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-101': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-100': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-099': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-098': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-097': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-096': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-095': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-094': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-093': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-092': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-091': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-090': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-089': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-088': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-087': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-086': Object.freeze({ home: 'none', note: 'a bejegyzés maga mondja ki, hogy gépi jele nincs (guard_note)' }),
  'KUKA-085': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-084': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-083': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-082': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-081': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-078': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-080': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-079': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-077': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-076': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-075': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-074': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-073': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-072': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-071': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-070': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-069': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-068': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-067': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-066': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-065': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-064': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-063': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-062': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-061': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-060': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-059': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-058': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-057': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-055': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-054': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-053': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-001': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-002': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-003': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-004': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-005': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-006': Object.freeze({ home: 'none', note: 'a bejegyzés maga mondja ki, hogy gépi jele nincs (guard_note)' }),
  'KUKA-007': Object.freeze({ home: 'v3', note: 'a jelek cél-fájljai ITT vannak — a jel FUT' }),
  'KUKA-008': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-009': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-010': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-011': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-012': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-013': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-014': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-015': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-016': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-017': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-018': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-019': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-020': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-021': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-022': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-023': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-024': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-025': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-026': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-027': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-028': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-029': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-030': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-031': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-032': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-033': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-034': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-035': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-036': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-037': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-038': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-046': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-045': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-044': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-043': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-042': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-051': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-050': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-049': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-048': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-047': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-041': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-039': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-040': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-052': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-056': Object.freeze({ home: 'vs', note: 'a jelek a V2 fájljaira mutatnak (vs repó) — itt NEM fut' }),
  'KUKA-112': Object.freeze({ home: 'vs', note: 'a BOARD bizonyíték-kapuja a V2 repóban él — a jel (verify:matrix-liveness MTX06 + board test:units) OTT fut' }),
  'KUKA-114': Object.freeze({ home: 'vs', note: 'a board BEFOGADÁSI SZERZŐDÉSE (EVC-01) a V2 repóban él — a jel (verify:matrix-profiles MPF12 + board egység-próbák) OTT fut' }),
  'KUKA-115': Object.freeze({ home: 'vs', note: 'az alkalmazhatóság-alap és a képesség-regiszter (CAP-01) a boardon él; a V3-oldali TANÚ-őr (verify:capability-witness) ehhez mér vissza' }),
  'KUKA-119': Object.freeze({ home: 'vs', note: 'a futtató és a befogadási szerződés a boardon él — a jel (MPF17) OTT fut' }),
  'KUKA-118': Object.freeze({ home: 'vs', note: 'a board hitelesítése és a közvetlen státusz-út a V2 repóban van — a jel (MPF10/MPF15) OTT fut' }),
  'KUKA-116': Object.freeze({ home: 'vs', note: 'a megkerülő HTTP-út és a kör-eszköz is a V2 repóban van — a jel (MPF10) OTT fut' }),
  'KUKA-117': Object.freeze({ home: 'vs', note: 'a darabszám-kapu és az eset-készlet a boardon él — a jel (MPF12/MPF13) OTT fut' }),
  'KUKA-121': Object.freeze({ home: 'v3', note: 'a beadvány-integritás és a befogadási korlát a V3 MAGBAN él — a jel (verify:v3ref: P-REV-claim-decide, M62–M64) ITT fut' }),
  // R73 (D-VS-3020) — mind a NÉGY a V3 MAGRÓL szól (tiltás-kérdés tárgya · hatáskör-feloldás ·
  // a parancs-út kontextusa · az ellentmondó rekord), tehát a jelük ITT fut.
  //
  // HELYESBÍTÉS (R75 §6, a KÜLSŐ TÁRGYALÓ FÉL): ez a blokk korábban EGY sorban sorolta fel a
  // `P-REV-ban-scope` és a `P-REV-ban-paths` próbákat „M70 · M71 · M72" falszifikációval — holott
  // az M71 a `P-REV-ban-scope`-ot buktatja, nem a `P-REV-ban-paths`-t. A külső fél ugyanezt a
  // csúszást találta meg máshol is: *„a hivatkozás nem bizonyít íróút-ellenőrzést; javítsuk a
  // kommentet a tényleges gépi jelre vagy ÉPÍTSÜK MEG a hiányzó jelet."* Mindkettőt megtettük: a
  // hivatkozások lentebb próbánként pontosak, a hiányzó íróút-jel pedig MEGSZÜLETETT (M75).
  // A tanulság a KUKA-126 alakja a SAJÁT jegyzeteinkre: egy hivatkozás, amit senki nem mér vissza,
  // DÍSZ — és rosszabb a hiányzónál, mert meglévő bizonyítéknak látszik.
  'KUKA-131': Object.freeze({ home: 'v3', note: 'a kérés-tengely védelme a `banScope.mjs` `banRequestFor`-jában él — a jel (verify:v3ref: P-REV-ban-scope (e) + M71) ITT fut' }),
  'KUKA-132': Object.freeze({ home: 'v3', note: 'a hatáskör-feloldás az AUT-01 modulban él — a jel (verify:v3ref: P-REV-ban-paths (d) + M70) ITT fut' }),
  'KUKA-133': Object.freeze({ home: 'v3', note: 'a belépési kontextus átadása a parancs- ÉS az elbírálási úton él — a jel (verify:v3ref: P-REV-ban-paths (g) + M67 + M77) ITT fut' }),
  'KUKA-134': Object.freeze({ home: 'v3', note: 'az ok↔fajta ellentmondás feloldója a `banScope.mjs` `banRecordIntegrity`-jében él — a jel (verify:v3ref: P-REV-ban-scope (f) + M72) ITT fut' }),
  'KUKA-120': Object.freeze({ home: 'v3', note: 'a felfüggesztés, az elbírálás és a jelzés-út a V3 MAGBAN él — a jel (verify:v3ref: P-REV-suspension + P-REV-claim-read, M56–M61) ITT fut' }),
  // R75 (D-VS-3021) — mind az ÖT a V3 MAGRÓL szól, tehát a jelük ITT fut. Négyet a KÜLSŐ TÁRGYALÓ
  // FÉL talált meg a saját, egy körrel korábbi javításomon; a KUKA-139-et a SAJÁT mutációs próbám.
  'KUKA-135': Object.freeze({ home: 'v3', note: 'a TELJES döntés (AUT-01 `executableRightAt`) és az egyetlen író a V3 magban él — a jel (verify:v3ref: P-REV-ban-paths (e)(f) + M73 + M75) ITT fut' }),
  'KUKA-136': Object.freeze({ home: 'v3', note: 'a művelet-tiltás tárolt hatóköre a `banScope.mjs`-ben él — a jel (verify:v3ref: P-REV-ban-paths (c) + P-REV-ban-matrix + M74 + M79) ITT fut' }),
  'KUKA-137': Object.freeze({ home: 'v3', note: 'a tárolt rekord integritás-feloldója a `banScope.mjs`-ben él — a jel (verify:v3ref: P-REV-ban-scope (g) + M76) ITT fut' }),
  'KUKA-138': Object.freeze({ home: 'v3', note: 'a belépési kontextus az elbírálási úton a V3 magban megy végig — a jel (verify:v3ref: P-REV-ban-paths (g) + M77) ITT fut' }),
  'KUKA-139': Object.freeze({ home: 'v3', note: 'a fixtúra ↔ termék-út megkülönböztetés a V3 próba-készletben él — a jel (v3ref:mutate M68 verdiktje + P-REV-ban-past (e)) ITT fut' }),
  'KUKA-140': Object.freeze({ home: 'v3', note: 'a mutációs battéria falióra-költségvetése a V3 mérőben él — a jel (v3ref:mutate falióra-sora + a TELJES V3 söprés) ITT fut' }),
  'KUKA-141': Object.freeze({ home: 'v3', note: 'a HATÁLYOSULÁSI PONT (EFF-01) a V3 magreferenciában él — a jel a `P-REV-effectuation` próba (négy idő-rögzítő út, visszamért invariánssal) + az M80/M81/M82/M88 mutációk ITT futnak' }),
  'KUKA-142': Object.freeze({ home: 'v3', note: 'a KIADOTT EREDMÉNY ADATKÖRE (DSC-01) a V3 magreferenciában él — a jel a `P-REV-result-scope` próba (pozitív kontroll + ellenpár + besorolás-hiány) + az M85/M86/M87 mutációk ITT futnak' }),
  'KUKA-143': Object.freeze({ home: 'v3', note: 'a tárolt műveleti hatókör szerkezeti épsége (OPS-01) a V3 magreferenciában él — a jel a `P-REV-ban-record-shape` próba (négy hibás alak + két jogos ellenpár) + az M83/M84 mutációk ITT futnak' }),
  'KUKA-144': Object.freeze({ home: 'v3', note: 'a mérő-eszköz kimenet-csonkulása a V3 futtatójában élt — a jel a `verify:kuka` KUKA-144 tiltó-mintája (process.exit a magreferencia futtatójában) + a `v3ref:mutate` mérőhiba-számlálója ITT fut' }),
  'KUKA-145': Object.freeze({ home: 'v3', note: 'a KIADOTT EREDMÉNY SÉMÁJA (DSC-01 v2) a V3 magreferenciában él — a jel a `P-REV-result-shape` próba (mélységi besorolás + levél-típus + nevezett hiány ÚTTAL) + az M89/M90 mutációk ITT futnak' }),
  'KUKA-146': Object.freeze({ home: 'v3', note: 'a KÖZÖS HATÁLYOSULÁSI PONT (EFF-01 v2, `effectuateWith`) a V3 magreferenciában él — a jel a `P-CMD-effectuation` próba + az M91/M92/M93 mutációk ITT futnak' }),
  'KUKA-147': Object.freeze({ home: 'v3', note: 'az ÍRÓ BELÉPÉSI PONTOK regisztere (ENT-01) a V3 magreferenciában él — a jel a `P-REV-entry-points` próba (60 cella, padlóval) + az M94/M95 mutációk ITT futnak' }),
  'KUKA-148': Object.freeze({ home: 'v3', note: 'az EGY AJTÓ (`store.tx`) a V3 magreferencia tárolójában él — a jel a `P-CMD-effectuation` (e) ága és a tároló kapuját hurkoló próbák ITT futnak' }),
  'KUKA-149': Object.freeze({ home: 'v3', note: 'a PRÓBA-TERVEZÉS tanulsága a V3 mérőben él — a jel a `P-CMD-effectuation` (b) ágának `mért pont elérve` mezője + az M93 mutáció verdiktje ITT fut' }),
  'KUKA-151': Object.freeze({ home: 'v3', note: 'az összefűzés beadvány-kapuja (MRG-01) a V3 mutációs battériájában él — a jel a `verify:unit-admission` ITT fut' }),
  'KUKA-152': Object.freeze({ home: 'v3', note: 'az adatkiadás hatályosulási pontja a V3 magreferencia `readCommandResult` útján él — a jel a `P-CMD-release-effectuation` próba ITT fut' }),
  'KUKA-153': Object.freeze({ home: 'v3', note: 'a mutációs horgony egyedisége a V3 battéria alkalmazójában él (`applyEdits`)' }),
  'KUKA-154': Object.freeze({ home: 'v3', note: 'a kötelező készlet rangsora a V3 norma-regiszterében és az összefűzésben él' }),
  'KUKA-155': Object.freeze({ home: 'v3', note: 'a próba-állapot zárt sémája a V3 beadvány-kapujában él (`probeStatusProblem`)' }),
  'KUKA-156': Object.freeze({ home: 'v3', note: 'az elvárt lánc-sorok a V3 norma-regiszteréből származnak (`expectedChainRows`)' }),
  'KUKA-157': Object.freeze({ home: 'v3', note: 'a környezeti felmentés mércéje a V3 külső-lánc futtatójában él (`environmentalObstacle`)' }),
  'KUKA-158': Object.freeze({ home: 'v3', note: 'a felülvizsgálati kör ellenpárja a V3 magreferencia fixtúrájában él (BIT.GRANT · feb-0)' }),
  'KUKA-159': Object.freeze({ home: 'v3', note: 'a tükör-esetek a V3 magreferencia próbáiban élnek (P-REV-grant-axis · P-ORG-basis) — a mutációs battéria méri' }),
  'KUKA-160': Object.freeze({ home: 'v3', note: 'a bukó gyermekfutás teljes nyoma a V3 külső-lánc futtatójában él (`child_trace`)' }),
  // R88 (D-VS-3027) — MINDKETTŐ a V3 MAGRÓL szól, tehát a jelük ITT fut: az egyik a felhatalmazási
  // alap azonosságáról (`authorityBasis.mjs`), a másik a tagságadás atomi határáról
  // (`bitemporal.mjs` + `store.mjs`). Mindkettőt a KÜLSŐ TÁRGYALÓ FÉL találta meg.
  'KUKA-161': Object.freeze({ home: 'v3', note: 'az alap azonossága a (basis_id, book_id) pár — a jel a P-ORG-basis (e) állítása + M121/M122/M123' }),
  'KUKA-162': Object.freeze({ home: 'v3', note: 'a tagságadás atomi határa — a jel az ÚJ P-ORG-grant-atomic próba + M124/M125/M126' }),
  'KUKA-163': Object.freeze({ home: 'v3', note: 'a mutáció-kontroll és a horgony élessége a V3 mutációs battériájában mérhető — a jel az M131/M120 elkapottsága és a `0 elavult horgony` rovat' }),
  'KUKA-164': Object.freeze({ home: 'v3', note: 'a művelet-azonosság és a kötelező tengely a V3 magban él — a jel a külső fél r92authz programja (a TELJES kiadás→beváltás úton, a keletkezett tagságra mérve) + a P-ORG-basis-limit (f)(g) állítása + M134–M137' }),
  'KUKA-165': Object.freeze({ home: 'v3', note: 'a külső-ellenőrző burkolók a V3 repóban élnek — a jel a `verify:external-checks` HOMOKOZÓS futása: a gyökér-feloldó és a forrás-kötés ott mérhető, ahol a kapu ténylegesen fut' }),
  'KUKA-150': Object.freeze({ home: 'v3', note: 'a RUN-02 futás-szerződés (darabolt futás) a V3 mutációs battériájában él — a jel az r79/U01 külső-ellenőrzés + az egység-fájl `evidence_bound` mezője ITT fut' }),
  'KUKA-166': Object.freeze({ home: 'v3', note: 'a norma-lánc klauzula↔állítás kötése a V3 magreferenciában él (`manifest.mjs` + `run.mjs`) — a jel ott mérhető, ahol a kötés SZÜLETIK' }),
  'KUKA-167': Object.freeze({ home: 'v3', note: 'a kiadási osztályozó és a mennyiség-szerződés VISZONYA a V3 magban él — a jel az M144 mutáció és a P-REV-result-shape (d) ága, ahol a VALÓDI eredmény megy át az osztályozón' }),
  'KUKA-168': Object.freeze({ home: 'v3', note: 'a mennyiség két szakasza (határ ↔ profil-kötés) a V3 magban él — a jel a P-BEM (i) ága (ugyanaz a szöveg MÁS profillal MÁS válasz) és a P-KSZ (g) darabos kanonikus alakja' }),
  'KUKA-169': Object.freeze({ home: 'v3', note: 'a kontextus ↔ tartalom szétválasztása a V3 bemeneti sémájában él — a jel a P-BEM (h) `unknown_field@warehouse_id` és a P-KSZ (d) `idempotency_conflict`' }),
  'KUKA-170': Object.freeze({ home: 'v3', note: 'a főkönyv tárolói őrei a V3 sémájában élnek — a jel a P-KSZ (i) NYERS tárolási próbája + az M146/M147 mutáció' }),
  // FIGYELEM, KIMONDVA: a KUKA-171 otthona azért 'v3', mert a jele ITT fut — de a jel NEM a hibát
  // (a söprés téves osztályozását) méri, hanem azt, hogy a nevesített blokkoló (OB-10) létezik és
  // megjelenik a nyitott blokkoló-listán. A hibára magára NINCS gépi jel, és ezt a bejegyzés
  // `guard_note`-ja is kimondja (KUKA-127: a gyengébb jel ERŐSSÉGÉT is ki kell írni).
  'KUKA-171': Object.freeze({ home: 'v3', note: 'a jel a `v3ref/norms.mjs` OB-10 blokkolója — a BLOKKOLÓ létét méri, NEM a söprés osztályozóját' }),
  'KUKA-172': Object.freeze({ home: 'v3', note: 'a darabszám deklarált otthona és a package.json parancs-sora ITT él — a jel a verify:unit-admission UAD08' }),
  'KUKA-173': Object.freeze({ home: 'v3', note: 'a hozzáférési kapu a V3 magban él — a jel a P-AUT-object-neutral próba + M149–M152' }),
  'KUKA-174': Object.freeze({ home: 'v3', note: 'a fixtúra a V3 próba-fájljában él — a jel ugyanannak a próbának az (a) ága' }),
  'KUKA-175': Object.freeze({ home: 'v3', note: 'a darabolás közös deklarációja a V3 külső-ellenőrző könyvtárában él — a jel a verify:unit-admission UAD08; a KÜLSŐ burkolók bontása kimondottan MÉRETLEN' }),
  'KUKA-199': Object.freeze({ home: 'v3', note: 'a beváltás plafon-szabálya a v3ref/invite.mjs-ben, a kimondott jogadás a v3ref/delegation.mjs-ben él — a jel a tiltó-minta (a beváltó nem hív adatköri jogadót), a P-CORE (c) szakasza és az M204 mutáció (verify:v3ref), a kilépési kódon' }),
  'KUKA-198': Object.freeze({ home: 'v3', note: 'a GPR-01 later_adapter_surface rétege és a kitöltött missing mezo (GP03) ITT el; RESZBEN gepi jel - hogy egy kovetkeztetes a testver-utakon is merve lett-e, arra nincs gepi jel, kimondva' }),
  'KUKA-197': Object.freeze({ home: 'v3', note: 'az or sajat harom ellenpeldaja a fajlban el (vs_verify_grant_paths.mjs --selftest), es a npm run verify:grant-paths mindharmat lefuttatja a kilepesi kodon - 3/3 bizonyitottan piros' }),
  'KUKA-196': Object.freeze({ home: 'v3', note: 'a jogadási utak nyilvántartása (GPR-01, contracts/grantPathRegistry.js) ITT él, és a npm run verify:grant-paths (GP01–GP05) mindkét irányban visszaméri — a jogadó írók halmaza a FORRÁSBÓL jön, nem kézi listából' }),
  'KUKA-195': Object.freeze({ home: 'v3', note: 'a kimondott ellenőrzési mód és a kötelező megadáskori verzió (ABL-01) a v3ref/authorityBasis.mjs-ben él — a jel az M194/M195 mutáció és a megerősített M190 (verify:v3ref), a kilépési kódon' }),
  'KUKA-194': Object.freeze({ home: 'v3', note: 'a kilépési takarító-háló a v3ref/store.mjs-ben él — a jel a pozitív minta; a szivárgás MÉRÉSÉRE nincs őr, ezt a bejegyzés kimondja' }),
  'KUKA-193': Object.freeze({ home: 'v3', note: 'a bírálati hatáskör alap-korlátja (ABL-01) a v3ref/authorityBasis.mjs-ben él, hívva az adjudication.mjs-ből és az authority.mjs-ből — a jel az M189–M193 mutáció (verify:v3ref), a kilépési kódon' }),
  'KUKA-192': Object.freeze({ home: 'v3', note: 'a megvonás két idő-tengelyes eseménye (SGR-01 + scope_grant_revocation) a v3ref/scopeGrant.mjs-ben él — a jel az M183–M187 mutáció (verify:v3ref), a kilépési kódon' }),
  'KUKA-191': Object.freeze({ home: 'v3', note: 'a ténylegesen megadott olvasási jog (SGR-01) a v3ref/scopeGrant.mjs-ben él — a jel az M177/M179/M181 mutáció és a membership_only tiltó-mintája' }),
  'KUKA-190': Object.freeze({ home: 'v3', note: 'a kiadási döntés-kapu (RSB-01) a v3ref/releaseScope.mjs-ben él — a jel a hat R47-es mutáció (verify:v3ref), a kilépési kódon' }),
  'KUKA-189': Object.freeze({ home: 'v3', note: 'a teljes tartalmi pillanatkép a v3ref/run.mjs próbáiban él — a jel az M173 és az M174 mutáció (verify:v3ref), a kilépési kódon' }),
  'KUKA-240': Object.freeze({ home: 'v3', note: 'a bemutató-buborék kitérése és átengedése a v3app/public/tour.mjs-ben él; a végigjárás a tests/e2e/v3app-r93.spec.mjs R93-01' }),
  'KUKA-241': Object.freeze({ home: 'v3', note: 'az üres osztálynév tiltása a v3app/public/tour.mjs-en fut, a lelet a meghívás-bemutató hatodik lépésén' }),
  'KUKA-242': Object.freeze({ home: 'v3', note: 'az AST-05 blokk-válasz a v3app/assistant/policy.mjs-ben és a v3app/server.mjs-ben él; élő mérés: verify:app-findings-r93' }),
  'KUKA-243': Object.freeze({ home: 'v3', note: 'a hordozott lezárás a v3app/public/tour.mjs + app.js párosban él; böngésző-tanú: R93-02/03' }),
  'KUKA-260': Object.freeze({ home: 'v3', note: 'a GLV-01 feloldó (scopeGrantLiveAt) a v3ref/releaseScope.mjs-ben él; hívja az idempotencia-kapu (v3ref/delegation.mjs), a kiadási döntés és a tag-lista (v3app/server.mjs) — jel: verify:kuka (három pozitív minta) + verify:v3ref (M316 · M317) + verify:app-findings-r125' }),
  'KUKA-261': Object.freeze({ home: 'v3', note: 'a tag-lista GET-je az írásmentes delegationCeilingOf-ot hívja a v3app/server.mjs-ben — jel: verify:kuka (pozitív minta) + verify:app-findings-r125 (C szakasz). KIMONDVA: a v3app-ra a mutációs battéria nem fut, rontás-kontroll ehhez nincs' }),
  'KUKA-255': Object.freeze({ home: 'v3', note: 'az ÍRÁSMENTES plafon-feloldó (delegationCeilingOf) a v3ref/delegation.mjs-ben él, és a megvonás döntési kapuja azt hívja — jel: verify:kuka (pozitív minták) + verify:v3ref (M310 · M311) + verify:app-findings-r123 (A szakasz, a jogosultsági táblák sor-számlálásával)' }),
  'KUKA-256': Object.freeze({ home: 'v3', note: 'az ATO-01 (atomicOutcome · refuseAndRollBack) a v3ref/authority.mjs-ben, a megadás atomi egysége a v3ref/delegation.mjs-ben — jel: verify:kuka + verify:v3ref (M312) + verify:app-findings-r123 (B szakasz). KIMONDVA: a megvonási ágon a burkolat hatása ma nem falszifikálható' }),
  'KUKA-257': Object.freeze({ home: 'v3', note: 'az üzleti idempotencia (scope_already_granted) a v3ref/delegation.mjs-ben, a nyugta a v3app/public/app.js-ben és a három nyelvcsomagban — jel: verify:kuka + verify:v3ref (M313 · M314) + verify:app-findings-r123 (C szakasz); böngésző-tanú: R123-C2' }),
  'KUKA-258': Object.freeze({ home: 'v3', note: 'a visszaállított plafon-rontás (M310) a v3ref/mutations.mjs-ben, a valódi szűk alap a v3ref/legacyAccountFixture.mjs-ben, a kiadott állítás a v3ref/run.mjs-ben — jel: verify:kuka + verify:v3ref (M310 CAUGHT)' }),
  'KUKA-259': Object.freeze({ home: 'v3', note: 'a mérés sorrendje a v3app/findings_r123.mjs-ben él: a fixture igazolása KÖZVETLEN alap-olvasással, a plafon-feloldó hívása a mérés UTÁN — jel: verify:kuka (pozitív minták) + verify:app-findings-r123 (a3)/(a9)' }),
  'KUKA-254': Object.freeze({ home: 'v3', note: 'a beváltás sikerének alanyhoz kötése a v3app/public/app.js doRedeem ágában él — jel: verify:kuka (pozitív összevetés + tiltott nézet-alapú név); böngésző-tanú: R112-I3' }),
  'KUKA-276': Object.freeze({ home: 'v3', note: 'a bemutató-motor harmadik állapota (navIntentFulfilled) és az egyetlen láthatóság-feloldó (isShown) a v3app/public/tour.mjs-ben él — jel: verify:kuka (három pozitív minta + a tiltott két-állapotú maradék-ág); ÉLŐ tanú: proof:demo-walk (két történet × 1280/390 px, kétszeri újraindítás, g1–g8 ellenpárok), rontás-próbával mérve' }),
  'KUKA-277': Object.freeze({ home: 'v3', note: 'a horgonyzott szöveg-mérés a tools/v3_demo_walk_proof.mjs-ben él — jel: verify:kuka (a csomagból olvasott elvárás + a hordozó elemre mért mondat, és a tiltott hatókör nélküli illesztés); ÉLŐ tanú: proof:demo-walk a10a (tartalom) és a10b (szállítás), külön-külön rontás-próbával pirosra váltva' }),
  'KUKA-278': Object.freeze({ home: 'v3', note: 'a kivétel MINDKÉT döntési ponton (checkRun + advance) a v3app/public/tour.mjs-ben él — jel: verify:kuka (két pozitív minta + a tiltott, kivétel nélküli alak); ÉLŐ tanú: proof:demo-walk, a két TELJES történet a végállapot önálló mérésével' }),
  'KUKA-279': Object.freeze({ home: 'v3', note: 'az átadás/visszaállás párja a v3app/public/app.js-ben él (pagehide + resumeTourAfterSwitch minden úton) — jel: verify:kuka; ÉLŐ tanú: proof:demo-walk, a történet a nézet-váltások után is folytatódik' }),
  'KUKA-280': Object.freeze({ home: 'v3', note: 'a haladás-napló és a rövid kattintás-határidő a tools/v3_demo_walk_proof.mjs-ben él — jel: verify:kuka; KIMONDVA: a tanú böngészőt igényel, nem része a verify:sweep-nek' }),
  'KUKA-281': Object.freeze({ home: 'v3', note: 'a visszaállás alapállása és a kimondott késleltetés a v3app/public/app.js-ben él (refreshMe) — jel: verify:kuka + ÉLŐ tanú: proof:demo-walk, rontás-ellenpárral' }),
  'KUKA-282': Object.freeze({ home: 'v3', note: 'a mobil menü közös feloldója (setNavOpen) és a sorrendfüggetlen újraértékelés a v3app/public/app.js-ben él — jel: verify:kuka (a kerülő-út tiltásával) + ÉLŐ tanú: proof:demo-walk (h2)–(h4)' }),
  'KUKA-283': Object.freeze({ home: 'v3', note: 'a bemutató-átadás nézet-PÁRJA a v3app/public/app.js-ben él (saveTourHandover + resumeTourAfterSwitch) — jel: verify:kuka + ÉLŐ tanú: proof:demo-walk (h1a)–(h1c), a VALÓDI actorSwitchReady-t hívva' }),
  'KUKA-284': Object.freeze({ home: 'v3', note: 'az írás-független darabolás és a modell-hívás feloldója a v3app/assistant/policy.mjs-ben, a kapu megszüntetése a v3app/server.mjs-ben — jel: verify:kuka + verify:app-findings-r142 (A·B)' }),
  'KUKA-285': Object.freeze({ home: 'v3', note: 'a találat-fajta feloldója (wordHitKind) és a gyenge találat jelölése a v3app/assistant/policy.mjs-ben él — jel: verify:kuka + verify:app-findings-r142 (C)' }),
  'KUKA-286': Object.freeze({ home: 'v3', note: 'a bemutató- és művelet-kötés EXPLICIT alakja a v3app/knowledge/coverage.mjs-ben (shared_tour · surface · ui_actions), a deklarációk a v3app/knowledge/features.mjs-ben — jel: verify:kuka + verify:lefedes (L10–L13) + verify:app-findings-r144 (A)' }),
  'KUKA-287': Object.freeze({ home: 'v3', note: 'az oldaltérkép EGY feloldója (sitemapPages) a v3app/public/help.mjs-ben, a menü-szerkezet tényleges bemenete a tools/v3_funkcio_leltar.mjs-ben, a nevezett elérhetetlenség a v3app/knowledge/coverage.mjs-ben — jel: verify:kuka (a hibás bemenet tiltásával) + verify:lefedes (L8) + verify:app-findings-r144 (B)' }),
  'KUKA-288': Object.freeze({ home: 'v3', note: 'a felajánlás-képzés EGY feloldója (offersFor) a v3app/assistant/policy.mjs-ben, a modell igazolt forrásainak bekötése a v3app/server.mjs-ben — jel: verify:kuka (a helyi-találat-only alak tiltásával) + verify:app-findings-r144 (C)' }),
  'KUKA-289': Object.freeze({ home: 'v3', note: 'a kimondható kizárási okok zárt listája (BLOCK_REASONS_TOLD) a v3app/assistant/policy.mjs-ben, a jog-válasz saját fajtája a v3app/server.mjs-ben — jel: verify:kuka + verify:app-findings-r144 (c5 · c5/2)' }),
  'KUKA-290': Object.freeze({ home: 'v3', note: 'a kéréskorlát vágása és a kimondott alsó korlát a v3app/server.mjs-ben (makeRateLimiter) — jel: verify:kuka (két pozitív + egy tiltó) + verify:app-findings-r154 (A: a1–a6)' }),
  'KUKA-291': Object.freeze({ home: 'v3', note: 'a hibás százalék-escape nevezett elutasítása a v3app/server.mjs-ben (serveStatic) — jel: verify:kuka + verify:app-findings-r154 (B: b1–b4, élő HTTP)' }),
  'KUKA-292': Object.freeze({ home: 'v3', note: 'a korlátos munkamenet-tár (makeSessionStore) ÉS a bekötése a v3app/server.mjs-ben — jel: verify:kuka (a második pozitív a BEKÖTÉST méri) + verify:app-findings-r154 (C/1 és C/2)' }),
  'KUKA-293': Object.freeze({ home: 'v3', note: 'a visszavétel-próbán törékenynek bizonyult mérés javítása a v3app/findings_r154.mjs-ben — jel: verify:kuka (két pozitív + egy tiltó a battéria fájlján); a visszavétel-próba maga NEM automatizált, ezt a bejegyzés kimondja' }),
  'KUKA-294': Object.freeze({ home: 'v3', note: 'a választás ÉS a találat ténye EGY feloldóban (pickFromAcceptLanguage) a v3app/public/i18n/languages.mjs-ben — jel: verify:kuka (két pozitív + egy tiltó) + verify:app-findings-r154 (D: d1–d4, d8)' }),
  'KUKA-295': Object.freeze({ home: 'v3', note: 'a q=0 kizárás a súly-szűrőben a v3app/public/i18n/languages.mjs-ben — jel: verify:kuka + verify:app-findings-r154 (D: d5–d7)' }),
  'KUKA-296': Object.freeze({ home: 'v3', note: 'a lejárat-kapu az OLVASÁSON (get/has/touch) a v3app/server.mjs-ben — jel: verify:kuka + verify:app-findings-r154 (E: e1–e3)' }),
  'KUKA-297': Object.freeze({ home: 'v3', note: 'a folytatást hordozó névtelen munkamenet külön kiszorítási osztálya és a kanonikus forrása (pending_intent) a v3app/server.mjs-ben — jel: verify:kuka (két pozitív) + verify:app-findings-r154 (E: e6–e9)' }),
  'KUKA-298': Object.freeze({ home: 'v3', note: 'a beszúrt sor sérthetetlensége (keep) és a belépetten született munkamenet a v3app/server.mjs-ben — jel: verify:kuka (két pozitív + egy tiltó) + verify:app-findings-r154 (E: e4, e5, e10)' }),
  'KUKA-299': Object.freeze({ home: 'v3', note: 'a vezérlő-karakter tiltása a bemeneti TÍPUSBAN (v3ref/inputSchema.mjs) — jel: verify:kuka (három pozitív) + verify:app-findings-r154 (F: f1–f4) + verify:v3ref (a mag mutációs battériája)' }),
  'KUKA-300': Object.freeze({ home: 'v3', note: 'a védett-lista kérdése jelöltekre szűkítve + az árva szerver-oldali állapot takarítása a v3app/server.mjs-ben — jel: verify:kuka (két pozitív + egy tiltó) + verify:app-findings-r154 (G: g1, g6, g7)' }),
  'KUKA-301': Object.freeze({ home: 'v3', note: 'a belépés rotációjának sorrendje (előbb törlés, aztán beszúrás) a v3app/server.mjs-ben — jel: verify:kuka + verify:app-findings-r154 (G: g5)' }),
  'KUKA-302': Object.freeze({ home: 'v3', note: 'a friss NÉVTELEN sor nem szoríthat ki belépettet a v3app/server.mjs-ben — jel: verify:kuka + verify:app-findings-r154 (G: g2, g3, g4)' }),
  'KUKA-303': Object.freeze({ home: 'v3', note: 'a nonempty_text fajta a v3ref/inputSchema.mjs-ben és a question mező párosítása a v3app/httpSchema.mjs-ben — jel: verify:kuka (két pozitív + egy tiltó) + verify:app-findings-r154 (H: h1–h6)' }),
  'KUKA-304': Object.freeze({ home: 'v3', note: 'a nulla bájt tilalma EGY feloldóban (nulCheck) és az e-mail vezérlő-karakter-tilalma a v3ref/inputSchema.mjs-ben — jel: verify:kuka (két pozitív) + verify:app-findings-r154 (I: i1–i3)' }),
  'KUKA-305': Object.freeze({ home: 'v3', note: 'a munkamenet-felvétel kimondott ténye (admitted) és a telt példány nevezett 503-a a v3app/server.mjs-ben — jel: verify:kuka (két pozitív) + verify:app-findings-r154 (I: i7, i8)' }),
  'KUKA-306': Object.freeze({ home: 'v3', note: 'az O(1) rövidre zárás és a névtelen-számláló a v3app/server.mjs-ben — jel: verify:kuka (két pozitív) + verify:app-findings-r154 (I: i4, i5, i6)' }),
  'KUKA-307': Object.freeze({ home: 'v3', note: 'a visszatöltés céljának név-ellenőrzése és idézőjelezése a tools/v3_pg_durability_proof.mjs-ben — jel: verify:kuka (két pozitív + egy tiltó); a lánc maga VALÓDI PostgreSQL-t kér, ezért a söprésben nem fut' }),
  'KUKA-308': Object.freeze({ home: 'v3', note: 'a kiszolgálás idejére védett munkamenet (pin/unpinAll) a v3app/server.mjs-ben — jel: verify:kuka (két pozitív + két tiltó) + verify:app-findings-r154 (J: j1–j5, I: i7)' }),
  'KUKA-309': Object.freeze({ home: 'none', note: 'a VISSZAVÉTEL-PRÓBA elvégzésének módjáról szól (kézi lépés), ezért nincs gépi jele — a bejegyzés ezt kimondja' }),
  'KUKA-310': Object.freeze({ home: 'v3', note: 'az átirat helyének EGY feloldója a tools/v3_fogyasztas_export.mjs-ben — jel: verify:kuka (egy pozitív + egy tiltó) + verify:app-findings-r154 (K: k1–k2)' }),
  'KUKA-311': Object.freeze({ home: 'v3', note: 'a plafon érvényesítése a pin elengedésekor a v3app/server.mjs-ben — jel: verify:kuka (két pozitív) + verify:app-findings-r154 (L: l1, l7, l2, l8)' }),
  'KUKA-312': Object.freeze({ home: 'v3', note: 'a sikertelen takarítás várólistája a v3app/server.mjs-ben — jel: verify:kuka (egy pozitív) + verify:app-findings-r154 (L: l3)' }),
  'KUKA-313': Object.freeze({ home: 'v3', note: 'a pinek jel szerinti fordított indexe a v3app/server.mjs-ben — jel: verify:kuka (egy pozitív + egy tiltó) + verify:app-findings-r154 (L: l4)' }),
  'KUKA-314': Object.freeze({ home: 'v3', note: 'a kérés EGY időbélyege és a touch válasza a v3app/server.mjs-ben — jel: verify:kuka (két pozitív + egy tiltó) + verify:app-findings-r154 (L: l5, l6)' }),
  'KUKA-315': Object.freeze({ home: 'none', note: 'MINTA-JEL NINCS, kimondva: maga az ÚT szűnt meg a következő körben (KUKA-316) — a pin elengedésekor már nincs söprés, tehát nincs hol megkérdezni a védettséget. A tanulság él, és a verify:app-findings-r154 g7 ellenpárja továbbra is méri, amit véd (az ÉLŐ munkamenet folytatása megmarad)' }),
  'KUKA-316': Object.freeze({ home: 'v3', note: 'a plafon a BESZÚRÁSNÁL dönt (overCap a tár méretére, beszúrás majd pin) és a munkamenethez kötött írás nevezett elutasítása a v3app/server.mjs-ben — jel: verify:kuka (két pozitív + egy tiltó) + verify:app-findings-r154 (M: m0–m5, L: l1)' }),
  'KUKA-317': Object.freeze({ home: 'v3', note: 'a forrás adatbázis-nevének dekódolása a tools/lib/vs_pg_target.mjs-ben — jel: verify:kuka (egy pozitív) + verify:app-findings-r154 (N: n1–n3); a PostgreSQL-lánc maga valódi adatbázist kér, ezért a söprésben nem fut' }),
  'KUKA-318': Object.freeze({ home: 'v3', note: 'a hibás visszatöltési cél jelzése ÉRTÉK NÉLKÜL a tools/v3_pg_durability_proof.mjs-ben — jel: verify:kuka (egy pozitív) + verify:app-findings-r154 (N: n4–n5)' }),
  'KUKA-319': Object.freeze({ home: 'v3', note: 'a többes átirat-találat nevezett elakadása a tools/v3_fogyasztas_export.mjs-ben — jel: verify:kuka (egy pozitív) + verify:app-findings-r154 (N: n6, az eszköz tényleges futtatásával)' }),
  'KUKA-320': Object.freeze({ home: 'v3', note: 'a q=0 kizárás megtartása és a `*` joker a v3app/public/i18n/languages.mjs-ben — jel: verify:kuka (két pozitív + egy tiltó) + verify:app-findings-r154 (O: o1–o7)' }),
  'KUKA-321': Object.freeze({ home: 'v3', note: 'a próba ideiglenes kimeneti útja a v3app/findings_r154.mjs-ben — jel: verify:kuka (egy pozitív); visszavétel-próba SZÁNDÉKOSAN nincs, mert az a könyvelt bizonyítékot írná felül' }),
  'KUKA-322': Object.freeze({ home: 'v3', note: 'a beszúrás elutasítása telt, csupa védett táron a v3app/server.mjs-ben — jel: verify:kuka (két pozitív) + verify:app-findings-r154 (P: p1–p7)' }),
  'KUKA-323': Object.freeze({ home: 'v3', note: 'a mérés alapsokaságának kimondása a v3app/findings_r154.mjs-ben — jel: verify:kuka (egy pozitív) + verify:app-findings-r154 (l4a, l4)' }),
  'KUKA-324': Object.freeze({ home: 'v3', note: 'a kétértelműség MŰKÖDŐ kiútjai a tools/v3_fogyasztas_export.mjs-ben — jel: verify:kuka (két pozitív) + verify:app-findings-r154 (Q: q5–q8)' }),
  'KUKA-325': Object.freeze({ home: 'v3', note: 'az út nélküli kapcsolati cím adatbázis-neve a tools/lib/vs_pg_target.mjs-ben — jel: verify:kuka (egy pozitív) + verify:app-findings-r154 (Q: q1–q4)' }),
  'KUKA-326': Object.freeze({ home: 'v3', note: 'a kapcsolati cím query-felülírásainak feloldása a tools/lib/vs_pg_target.mjs-ben — jel: verify:kuka (két pozitív) + verify:app-findings-r154 (R: r1–r5)' }),
  'KUKA-327': Object.freeze({ home: 'v3', note: 'a --transcript kötése a kért munkamenethez a tools/v3_fogyasztas_export.mjs-ben — jel: verify:kuka (egy pozitív) + verify:app-findings-r154 (R: r8–r9)' }),
  'KUKA-328': Object.freeze({ home: 'v3', note: 'a munkamenet-plafon pozitív EGÉSZ volta a v3app/server.mjs-ben — jel: verify:kuka (egy pozitív) + verify:app-findings-r154 (R: r6–r7)' }),
  'KUKA-329': Object.freeze({ home: 'v3', note: 'a friss, állapot nélküli sor elsőbbsége a kiszorításban, a v3app/server.mjs-ben — jel: verify:kuka (egy pozitív) + verify:app-findings-r154 (g7, g8)' }),
  'KUKA-330': Object.freeze({ home: 'v3', note: 'a nyelvi kizárás tartomány-illesztése a v3app/public/i18n/languages.mjs-ben — jel: verify:kuka (egy pozitív) + verify:app-findings-r154 (R: r10–r11) + verify:i18n' }),
  'KUKA-331': Object.freeze({ home: 'v3', note: 'az igény szerinti munkamenet (átmeneti sor + materialize) a v3app/server.mjs-ben — jel: verify:kuka (két pozitív + egy tiltó) + verify:app-findings-r154 (S: s1–s11) + app:selfcheck' }),
  'KUKA-332': Object.freeze({ home: 'v3', note: 'a függő szándék lejárata a v3ref/invite.mjs-ben, az amortizált takarítás a v3app/server.mjs-ben — jel: verify:kuka (három pozitív + két tiltó) + verify:v3ref (P-K03-intent-expiry · M208/M209) + verify:app-findings-r154 (T: t1–t6)' }),
  'KUKA-333': Object.freeze({ home: 'v3', note: 'a kötelező böngésző-kapu a tools/vs_verify_browser_gate.mjs-ben és a package.json verify: névterében — jel: verify:kuka (három pozitív + két tiltó) + maga a verify:browser-gate (a söprés része)' }),
  'KUKA-334': Object.freeze({ home: 'v3', note: 'az elvégzett lépés megszólalása és a tájékoztató várakozás egy otthona a v3app/public/tour.mjs-ben, a mondat a három nyelvcsomagban — jel: verify:kuka (öt pozitív + egy tiltó) + verify:i18n + verify:browser-gate (R89-06)' }),
  'KUKA-335': Object.freeze({ home: 'v3', note: 'a váltás-lépés vezérlő-ellenőrzése a v3app/public/tour.mjs-ben — jel: verify:kuka (egy pozitív) + verify:browser-gate (R91-03 · R93)' }),
  'KUKA-336': Object.freeze({ home: 'v3', note: 'a két szereplős történetek járója a tests/e2e/v3app-r93.spec.mjs-ben — jel: verify:kuka (három pozitív + egy tiltó) + verify:browser-gate (az R93 elszámolása)' }),
  'KUKA-337': Object.freeze({ home: 'v3', note: 'a védő kapuk idő-iránya a v3ref/banScope.mjs és a v3ref/suspension.mjs kérés-óra ágán, a nevezett zárás a v3ref/reentryGate.mjs-ben — jel: verify:v3ref (P-AUTHZ-protective-clock · M210/M211/M212) + verify:kuka (három pozitív + két tiltó)' }),
  'KUKA-338': Object.freeze({ home: 'v3', note: 'az átvitt korlát alakjának olvasata a v3ref/delegation.mjs delegationCeilingOf-jában — jel: verify:v3ref (P-AUTHZ-parent-limit · M213/M214) + verify:kuka (két pozitív + egy tiltó)' }),
  'KUKA-253': Object.freeze({ home: 'v3', note: 'a nyelvcsomagból épülő főszöveg (refusalText · inviteNextKey · actingAsText) a v3app/public alatt él — jel: verify:kuka (négy tiltott + három pozitív minta) és verify:i18n I18N08' }),
  'KUKA-252': Object.freeze({ home: 'v3', note: 'a közös lezáró (carryTourBeforeSwitch) a v3app/public/app.js-ben, a lezárás oka a tour.mjs pillanatképén él — jel: verify:kuka; böngésző-tanú: R109-03 + R112-I1/I2' }),
  'KUKA-251': Object.freeze({ home: 'v3', note: 'a nevezett személyes-tér kivétel (personal_space_ok) a V3 tudás-regiszterében és a közös elérhetőségi feloldóban él — jel: verify:assistant AST02 (a kivétel és a kezelői tiltás EGY állításban), böngésző-tanú a tests/e2e/v3app-r109-invite.spec.mjs R109-01' }),
  'KUKA-250': Object.freeze({ home: 'v3', note: 'a megszakítás alatt leállított ellenőrző NEGYEDIK, nevezett kimenete (MEGSZAKÍTVA) a söprés osztályozójában él — jel: verify:child-runner CR16 és a verify:kuka pozitív/tiltó mintái a tools/vs_verify_sweep.mjs-en' }),
  'KUKA-249': Object.freeze({ home: 'v3', note: 'a megszakítási jelentés BIZTOS csatornája (ITR-01, tools/lib/vs_interrupt_report.mjs), a futtató kilépés előtti kiírása és a türelem/bizonyíték szétválasztása (forceCuts) ITT él; jel: verify:child-runner CR16, két ellenpróbával' }),
  'KUKA-248': Object.freeze({ home: 'v3', note: 'a közös megszakítási állapot (SHD-01, tools/lib/vs_shutdown_state.mjs), az indítási kapu (CHR-01) és a sorozat megszakítás-kapuja (SEQ-01) ITT él; jel: verify:child-runner CR14–CR15, ellenpróbával' }),
  'KUKA-247': Object.freeze({ home: 'v3', note: 'a sorozat-vezérlő (SEQ-01, tools/lib/vs_sweep_sequence.mjs) és a futtató megszakítási útja (CHR-01) ITT él; jel: verify:child-runner CR09–CR13' }),
  'KUKA-246': Object.freeze({ home: 'v3', note: 'a védett futtató (CHR-01, tools/lib/vs_child_runner.mjs) és a söprés bekötése ITT él; jel: verify:child-runner CR01–CR08' }),
  'KUKA-245': Object.freeze({ home: 'v3', note: 'a nyelv-emlékezet (LNG-02) és az EGY bejárat a v3app/public-ban él; tanú: verify:app-findings-r95 + tests/e2e/v3app-r97.spec.mjs' }),
  'KUKA-244': Object.freeze({ home: 'v3', note: 'a monoton nyelv-generáció a v3app/public/app.js-ben él; böngésző-tanú: R93-04/05/06' }),
  'KUKA-188': Object.freeze({ home: 'v3', note: 'az összefűzés kanonikus újraszámolása a v3ref/mutate.mjs-ben él — a jel a csomag-generátor teljes mező-összevetése (kilépési kód 3)' }),
  'KUKA-187': Object.freeze({ home: 'v3', note: 'a WRONG_CATCHER ítélet a V3 battériájában él (verify:v3ref) — a tanulság viszont a mutáció MEGÍRÁSÁRÓL szól, arra gépi jel nincs' }),
  'KUKA-186': Object.freeze({ home: 'v3', note: 'a belső forrás-kötések ellenőrzése a csomag-generátorban él — a jel az NCP02-25 eset, a kilépési kódon' }),
  'KUKA-185': Object.freeze({ home: 'v3', note: 'a kimeneti szerződés (ROW_CONTRACT) és a teljes mező-összevetés itt fut — a jel a proof:norm-chain-package 25 esete' }),
  'KUKA-184': Object.freeze({ home: 'v3', note: 'a sémaverzió a KANONIKUS bevét-úton mérve — a jel a P-KSZ-ledger-truth új állítása és az M163 mutáció' }),
  'KUKA-183': Object.freeze({ home: 'v3', note: 'a soha nem dobó diagnosztikai megjelenítő (showValue) itt él — a jel a P-BEM-input-schema nyolc alakja és a verify:kuka tiltó-mintája' }),
  'KUKA-182': Object.freeze({ home: 'v3', note: 'a forrás-kötés és a kanonikus ítélő újrafuttatása a csomag-generátorban él — a jel a proof:norm-chain-package húsz esete, a kilépési kódon' }),
  'KUKA-239': Object.freeze({ home: 'v3', note: 'a függvény-hatókörű mérés itt él — a jel a tools/vs_verify_tutor.mjs faqHtml-test kivágása és a hamis zöld ellenpróbája' }),
  'KUKA-238': Object.freeze({ home: 'v3', note: 'a nyelv-feloldó szerződés szerinti hívása itt él — a jel a server.mjs és az app.js hívás-mintája, plusz a findings_r91 B/(c) Accept-Language mérése' }),
  'KUKA-237': Object.freeze({ home: 'v3', note: 'a nyelv-független próba-állítás itt él — a jel a tests/e2e/helpers.mjs viselkedés-mérése és a beégetett mondat tiltása' }),
  'KUKA-236': Object.freeze({ home: 'v3', note: 'a művelet-paraméterek zárt mező-listája itt él — a jel a features.mjs ACTION_PARAMS, a policy.mjs param_unknown ága és a findings_r91 F) rekesze' }),
  'KUKA-235': Object.freeze({ home: 'v3', note: 'a szolgáltatói válasz-szerződés itt él — a jel a policy.mjs verifyModelAnswer, a server.mjs forrás- és előzmény-kötése, plusz a findings_r91 D)/E) rekesze' }),
  'KUKA-234': Object.freeze({ home: 'v3', note: 'a teljes nyelvi út itt él — a jel a nyelvcsomagok SRV csoportja, az app.js személyhez kötött tárolása és a findings_r91 B) rekesze' }),
  'KUKA-233': Object.freeze({ home: 'v3', note: 'a közös elérhetőségi feloldó itt él — a jel a policy.mjs availabilityOf/searchableFaqIds, a features.mjs audience mezője és a verify:tutor TUT11' }),
  'KUKA-232': Object.freeze({ home: 'v3', note: 'a nyilvános tudás-út itt él — a jel a features.mjs requires_anonymous, az app.js notAvailable ága és a böngésző-próba R91-04' }),
  'KUKA-231': Object.freeze({ home: 'v3', note: 'a bemutató-befejezés szerződése itt él — a jel a tour.mjs finishRun/skipStep, az app.js hívása és a böngésző-próba R91-01/02' }),
  'KUKA-230': Object.freeze({ home: 'v3', note: 'a bezárt súgó-panel rajzolás-tilalma itt él — a jel a v3app/public/app.js renderHelp nyitva-lét kapuja és a böngésző-próba help-close DARABSZÁM-mérése' }),
  'KUKA-229': Object.freeze({ home: 'v3', note: 'az irány-független rejtés és a képernyőhöz igazodó lenyíló itt él — a jel a v3app/public/style.css clip-path/logikai tulajdonságai és a böngésző-próba R89-08 elérhetőség-mérése' }),
  'KUKA-228': Object.freeze({ home: 'v3', note: 'a feltárásra váró bemutató-lépés itt él — a jel a v3app/public/tour.mjs revealerOf/isPending ága, az app.js hostTour-ja és a verify:tutor TUT05 feltáró-rekesze' }),
  'KUKA-227': Object.freeze({ home: 'v3', note: 'a súgó-panel nézet-bélyege itt él — a jel a v3app/public/app.js openHelp stampEl hívása és a böngésző-próba R89-07/R89-09 kérdés-küldése' }),
  'KUKA-226': Object.freeze({ home: 'v3', note: 'a próbapad KIMONDOTT művelet-türelme itt él — a jel a playwright.config.mjs actionTimeout-ja és a tests/e2e/v3app-r89-tutor.spec.mjs tiltó-mintája' }),
  'KUKA-225': Object.freeze({ home: 'v3', note: 'a sablonból születő felületi pontok deklarált családja itt él — a jel a tools/vs_verify_tutor.mjs GENERATED_FAMILIES tábla és a kétirányú mérése' }),
  'KUKA-224': Object.freeze({ home: 'v3', note: 'az AI-szerződés betartása a V3 segédjében él — a jel a v3app/assistant/policy.mjs localAnswer ága és a verify:tutor TUT03 rekesze' }),
  'KUKA-223': Object.freeze({ home: 'v3', note: 'a kereső nyelvi alapja itt él — a jel a v3app/assistant/policy.mjs wordHit/STOPWORDS, a nyelvcsomagok SEARCH csoportja és a verify:tutor QUESTION_SET' }),
  'KUKA-222': Object.freeze({ home: 'v3', note: 'a segéd fiók-kapuja itt él — a jel a v3app/assistant/policy.mjs scope-ellenőrzése, a features.mjs scope mezője és a findings_r89 C) rekesze' }),
  'KUKA-221': Object.freeze({ home: 'v3', note: 'a mennyiség-jelvény kód-alapú döntése itt él — a jel a v3app/public/app.js qualityBadge, a demoData.mjs QUALITY_CODES és a QUALITY_LABEL tiltó-mintája' }),
  'KUKA-220': Object.freeze({ home: 'v3', note: 'a kérés-kimenet a fajtájához kötve a V3 felületén él — a jel a v3app/public/app.js requestOutcome ága és a tests/e2e/v3app-r85.spec.mjs F85-04, F85-04/b rekesze' }),
  'KUKA-219': Object.freeze({ home: 'v3', note: 'a fiókhoz rögzített bemutató-csomag a V3 héjában és felületén él — a jel az app_demo_fixture tábla, a demoFor(fixtureId) és a tests/e2e/v3app-r85.spec.mjs F85-03 rekesze' }),
  'KUKA-218': Object.freeze({ home: 'v3', note: 'a közös nézet-ürítés a V3 felületén él — a jel a resetViewCaches és a tests/e2e/v3app-r85.spec.mjs F85-02 rekesze' }),
  'KUKA-217': Object.freeze({ home: 'v3', note: 'a létrehozás szerveroldali személy-kötése a V3 héjában él — a jel a POST /api/workspaces kontextus-kapuja és a tests/e2e/v3app-r85.spec.mjs F85-01 rekesze' }),
  'KUKA-216': Object.freeze({ home: 'v3', note: 'a verdikt a mért hatókörhöz kötve — a jel a tests/e2e/v3app-r81-ux.spec.mjs „reszben_bizonyitva" szava és a HASZNALATI_HELYZETEK táblája' }),
  'KUKA-215': Object.freeze({ home: 'v3', note: 'a három kimenet külön szava a V3 felületén él — a jel a v3app/public/app.js requestOutcome feloldója és a tests/e2e/v3app-r83.spec.mjs F83-05 rekesze' }),
  'KUKA-214': Object.freeze({ home: 'v3', note: 'a paraméteres szótár a V3 felületén él — a jel a v3app/public/texts.mjs TPL/tpl és a verify:kuka tiltó-mintái az app.js-en' }),
  'KUKA-213': Object.freeze({ home: 'v3', note: 'a készlet-jellegű nézetek közös kapuja és a kimondott mintacsomag-hozzárendelés a V3 felületén él — a jel a stockGate, a DEMO_EMPTY és a tests/e2e/v3app-r83.spec.mjs F83-03 rekesze' }),
  'KUKA-212': Object.freeze({ home: 'v3', note: 'a megőrzött kitöltés és a nem mentett munka kérdése a V3 felületén él — a jel a restoreForms, az unsaved-dialog és a tests/e2e/v3app-r83.spec.mjs F83-02 rekesze' }),
  'KUKA-211': Object.freeze({ home: 'v3', note: 'a megnyitáskori nézet-bélyeg a V3 felületén él — a jel a stampOf/refuseStale és a tests/e2e/v3app-r83.spec.mjs F83-01 két rekesze' }),
  'KUKA-210': Object.freeze({ home: 'v3', note: 'az EGY szövegforrás (v3app/public/texts.mjs) a V3 felületén él — a jel a tests/e2e/v3app-r81-ux.spec.mjs UX-07 szöveg-mérése és a verify:kuka tiltó-mintái' }),
  'KUKA-209': Object.freeze({ home: 'v3', note: 'a lekérés nézetenként EGYSZER indul magától a V3 felületén — a jel a tests/e2e/v3app-r79.spec.mjs kérés-számlálója és a verify:kuka tiltó-mintája' }),
  'KUKA-208': Object.freeze({ home: 'v3', note: 'az ÍRÁS alany+könyv kötése (KTX-03) a V3 héjában, séma-regiszterében és felületén él — a jel a verify:app-findings-r79 mátrixa és a tests/e2e/v3app-r79.spec.mjs azonos cégen belüli fiókváltása' }),
  'KUKA-207': Object.freeze({ home: 'v3', note: 'a nézet-kötés szabálya külön, behúzható modulban él (v3app/public/contextBinding.mjs) — a jel a verify:app-findings-r79 igazság-táblája ugyanazon a fájlon, és a böngésző hibabeviteles próbája' }),
  'KUKA-206': Object.freeze({ home: 'v3', note: 'a származtatott bizonyíték-lap hatókör-jelölése a V3 böngésző-csomagjában él — a jel a verify:app-findings-r77 R77 §4 (c/0) szakasza és a tiltó-minta a régi tartalék ágra' }),
  'KUKA-205': Object.freeze({ home: 'v3', note: 'az atomi munkakörnyezet-indítás (PRV-01) és az írás ELŐTTI azonosság-kérdés a V3 magjában és héjában él — a jel a verify:app-findings-r77 F77-02 szakasza (az eredeti kérés, normalizálás-után-üres alakok, vezérelt bukás egy későbbi lépésben, sor-számlálással) és a böngésző-próba' }),
  'KUKA-204': Object.freeze({ home: 'v3', note: 'az olvasás nézethez kötése (KTX-02) a V3 héjában, séma-regiszterében és felületén él — a jel a verify:app-findings-r77 F77-01 szakasza és a tests/e2e/v3app-r77.spec.mjs két lapos, közös sütis versenye' }),
  'KUKA-203': Object.freeze({ home: 'v3', note: 'a HTTP-határ séma-regisztere (HTP-01) és a közös BEM-01 motor a V3 próba-alkalmazásában és magjában él — a jel a verify:app-findings F75-03 szakasza (az eredeti lelet bemenetével), a verify:app-selfcheck és a böngésző-csomag' }),
  'KUKA-202': Object.freeze({ home: 'v3', note: 'a kontextus-kötés (KTX-01) a V3 héjában és felületén él — a jel a verify:app-findings F75-02 szakasza és a tests/e2e/v3app-r75.spec.mjs valódi böngésző-versenye (visszatartott válaszok, második lap)' }),
  'KUKA-201': Object.freeze({ home: 'v3', note: 'a megerősítés újrakérése (CHR-01) a V3 magjában és héjában él — a jel a verify:app-findings F75-01 szakasza, támogatott órával (nem valódi 24 óra), és a böngésző-próba a felhasználó útján' }),
  'KUKA-200': Object.freeze({ home: 'v3', note: 'a bizonyíték-újrahasználat feloldója (SRU-01) és a söprés bekötése a V3 szerszám-könyvtárában él — a jel a verify:sweep-reuse SRU01–SRU10, szintetikus git-repón, a VALÓDI söprés alfolyamatként futtatva' }),
  'KUKA-181': Object.freeze({ home: 'v3', note: 'a két konkrét HAMIS lehetetlenségi mondatra tiltó-minta áll a V3 norma-fájlján — az viszont, hogy egy ÚJ hiány-indok igaz-e, PRÓZA, és arra a bejegyzés maga mondja ki, hogy gépi jel nincs' }),
  'KUKA-180': Object.freeze({ home: 'v3', note: 'a művelet-név saját kulcsos feloldója és a sémaverzió határa a V3 magreferenciájában él — a jel a P-BEM-input-schema (j)/(k) ága és az M153/M154/M158 mutáció' }),
  'KUKA-179': Object.freeze({ home: 'v3', note: 'a csomag-generátor és az ellenpár-battériája ITT van — a jel a proof:norm-chain-package tíz piros visszalépése és két pozitív ellenpárja, a kilépési kódon' }),
  'KUKA-178': Object.freeze({ home: 'v3', note: 'a tisztaság-tanú szigorított olvasata és a tanú-hitelesítő (freshUnitWitness) a V3 magreferenciájában él — a jel a v3ref/unitFailureKind.test.mjs tíz esete (hat F35-01 ellenpár + négy tanú-frissesség) és a verify:v3ref kilépési kódja' }),
  'KUKA-177': Object.freeze({ home: 'v3', note: 'a darabszám-származtatás és a bukás-okot eldöntő feloldó a V3 magreferenciájában él — a jel a v3ref/unitFailureKind.test.mjs négy ellenpárja és a verify:v3ref kilépési kódja' }),
  'KUKA-176': Object.freeze({ home: 'v3', note: 'a verdikt-szerződés és a hibás-alak ág a V3 szerszám-könyvtárában él — a jel a verify:sweep-verdict SWV07, ellenpárokkal és VALÓDI gyermek-folyamattal' }),
});

function homeOf(id) { return (GUARD_HOME[id] || null); }
function idsHomedIn(home) { return Object.keys(GUARD_HOME).filter((k) => GUARD_HOME[k].home === home); }

module.exports = { GUARD_HOME_CONTRACT_ID, GUARD_HOME, VS_HOMED_CEILING, homeOf, idsHomedIn };
