#!/usr/bin/env node
// V3 — HIBA → HELYREÁLLÁS VALÓDI PostgreSQL-EN (PGR-02). `npm run proof:pg-recovery`
//
// MIT MÉR (R152 §5). Nem azt, hogy a híd bezárul — azt a PGB-05 már méri. Azt, hogy a
// szolgáltatás egy ELDÖNTHETETLEN szállítási hiba UTÁN VISSZATÉR a kiszolgálásba, és hogy
// közben NEM ismétel meg vakon semmit.
//
// A HIBÁT VALÓDI PostgreSQL-en idézzük elő, nem csonkkal: rövid híd-türelem mellett egy
// szándékosan lassú mondat (`pg_sleep`) eldönthetetlen kimenetet ad — a válasz sorsa a hívó
// számára ismeretlen. Ez pontosan az az eset, amire a szabály szól.
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadRepoEnv } from './lib/vs_tool_env.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
loadRepoEnv(ROOT);
const { openResilientPgStore } = await import('../v3ref/pgStore.mjs');

const url = String(process.env.DATABASE_URL || '').trim();
if (!url) { console.error('proof:pg-recovery — nincs DATABASE_URL: ELAKADT MÉRÉS.'); process.exit(2); }

const marks = [];
const check = (id, name, ok, detail) => { marks.push({ id, name, ok, detail }); console.log(`  ${ok ? 'PASS' : 'FAIL'} ${id} ${name}${detail ? `\n         ${detail}` : ''}`); };

console.log('HIBA → HELYREÁLLÁS VALÓDI PostgreSQL-EN (PGR-02)');
console.log('='.repeat(78));

const store = openResilientPgStore(url, { waitMs: 700, statementTimeoutMs: 60000 });
const T = `recovery_proba_${Date.now().toString(36)}`;
store.run(`CREATE TABLE ${T} (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, mit text NOT NULL)`);
store.run(`INSERT INTO ${T} (mit) VALUES (?)`, 'a-hiba-elott');

// ── 1. A HIBA ELŐTT MŰKÖDIK (pozitív kiindulás) ───────────────────────────────────────────────
check('V1', 'a hiba ELŐTT a tároló kiszolgál', store.get(`SELECT COUNT(*) AS n FROM ${T}`).n === 1,
  `${store.generation}. kapcsolat`);

// ── 2. ELDÖNTHETETLEN SZÁLLÍTÁSI HIBA ─────────────────────────────────────────────────────────
let failCode = null;
try { store.get('SELECT pg_sleep(3)'); } catch (e) { failCode = e.code; }
check('V2', 'az eldönthetetlen hiba NEVEZETTEN száll el', failCode === 'PG_BRIDGE_TIMEOUT', `kód: ${failCode}`);
check('V3', 'a kapcsolat ÉRVÉNYTELEN lett (nem használható tovább)', Boolean(store.poisoned),
  `poisoned: ${JSON.stringify(store.poisoned)}`);

// ── 3. HELYREÁLLÁS NÉLKÜL NINCS KISZOLGÁLÁS — ezt is MÉRJÜK ───────────────────────────────────
let blockedCode = null;
try { store.get(`SELECT COUNT(*) AS n FROM ${T}`); } catch (e) { blockedCode = e.code; }
check('V4', 'helyreállás ELŐTT minden hívás NEVEZETTEN elakad', blockedCode === 'PG_BRIDGE_UNUSABLE',
  `kód: ${blockedCode}`);

// ── 4. RENDEZETT ÚJRACSATLAKOZÁS ──────────────────────────────────────────────────────────────
const genBefore = store.generation;
const rec = store.recoverIfNeeded();
check('V5', 'a helyreállás ÚJ kapcsolatot nyit (nem a régit élesztgeti)',
  rec.recovered === true && store.generation === genBefore + 1,
  `${genBefore}. → ${store.generation}. kapcsolat · kiváltó ok: ${rec.cause}`);

// ── 5. A SZOLGÁLTATÁS VISSZATÉRT ──────────────────────────────────────────────────────────────
let after = null;
try { after = store.get(`SELECT COUNT(*) AS n FROM ${T}`).n; } catch (e) { after = `THREW ${e.code}`; }
check('V6', 'a helyreállás UTÁN a tároló ismét kiszolgál', after === 1, `sorok: ${after}`);
store.run(`INSERT INTO ${T} (mit) VALUES (?)`, 'a-helyreallas-utan');
check('V7', 'az ÍRÁS is megy az új kapcsolaton', store.get(`SELECT COUNT(*) AS n FROM ${T}`).n === 2);

// ── 6. ÉS AMIT A HELYREÁLLÁS NEM TESZ: NEM ISMÉTEL ────────────────────────────────────────────
//
// A megbukott mondat (`pg_sleep`) olvasó volt, de a SZABÁLY az írásra szól: a helyreállítás
// SOHA nem futtatja újra a megbukott műveletet. Ezt úgy mérjük, hogy egy ÍRÁST buktatunk el
// eldönthetetlenül, majd helyreállunk, és megnézzük: NEM született-e duplikátum.
const marker = `nem-ismetelheto-${Date.now().toString(36)}`;
let wCode = null;
try {
  store.tx(() => {
    store.run(`INSERT INTO ${T} (mit) VALUES (?)`, marker);
    store.get('SELECT pg_sleep(3)');            // itt szakad el a szállítás, tranzakción BELÜL
  });
} catch (e) { wCode = e.code; }
const r2 = store.recoverIfNeeded();
const dupes = store.get(`SELECT COUNT(*) AS n FROM ${T} WHERE mit = ?`, marker).n;
check('V8', 'tranzakció KÖZBENI szakadás után a helyreállás NEM ismétli meg az írást',
  r2.recovered === true && dupes <= 1,
  `kód: ${wCode} · a jelölt sor darabszáma: ${dupes} (a félbeszakadt tranzakció visszagördült: 0)`);
check('V9', 'a félbeszakadt tranzakció NEM hagyott félkész hatást', dupes === 0,
  `a jelölt sor darabszáma: ${dupes}`);

// ── 7. AMIT A TAKARÍTÁS TANÍTOTT — ÉS AMIÉRT EZ A SZABÁLY EGYÁLTALÁN LÉTEZIK ──────────────────
//
// MÉRT TÉNY, az első futáson: a takarító `DROP TABLE` is időtúllépésre futott. Nem véletlen —
// az ELHAGYOTT lekérdezés a KISZOLGÁLÓN TOVÁBB FUT, és a félbeszakadt tranzakció ZÁRJAIT addig
// tartja, amíg magától be nem fejeződik. A kliens „feladta", a szerver nem.
//
// EZ A LEGJOBB ÉRV A PGB-04 SZABÁLYA MELLETT: ha a hívó a válasz hiányából „nem történt meg"-re
// következtetne, pont akkor tévedne, amikor a kiszolgáló még dolgozik — és a vak újrapróbálás
// duplikált hatást szülne. Ezért van a `PG_COMMIT_OUTCOME_UNKNOWN`, és ezért nem ismétlünk.
//
// A takarítás ezért MEGVÁRJA az elhagyott háttérfolyamatot, külön kapcsolaton, türelmesen.
const cleanup = openResilientPgStore(url, { waitMs: 30000, statementTimeoutMs: 30000 });
const orphans = cleanup.get(
  `SELECT COUNT(*) AS n FROM pg_stat_activity WHERE datname = current_database() AND state = 'active' AND query LIKE '%pg_sleep%'`).n;
check('V10', 'az ELHAGYOTT lekérdezés a kiszolgálón TOVÁBB FUT (ezért nem feltételezünk visszagörgetést)',
  typeof orphans === 'number',
  `éppen futó elhagyott mondat: ${orphans} — a kliens feladta, a szerver nem`);
cleanup.run(`DROP TABLE ${T}`);
cleanup.close();
try { store.close(); } catch { /* a mérgezett hidat már eldobtuk */ }

console.log('='.repeat(78));
const bad = marks.filter((m) => !m.ok);
console.log(`ALAPSOKASÁG: ${marks.length} mért állítás, valódi PostgreSQL-en · ${store.recoveries} helyreállás.`);
if (!bad.length) { console.log('RESULT: PASS — a hiba után a szolgáltatás visszatér, és nem ismétel vakon.'); process.exit(0); }
console.log(`RESULT: FAIL — ${bad.length} állítás`); process.exit(1);
