#!/usr/bin/env node
// V3 — A KANONIKUS SÉMA PostgreSQL-ALAKJA (PGS-01). FEJLESZTŐI SZERSZÁM, nem futásidejű kód.
//
// MIT CSINÁL. A `v3ref/store.mjs` KANONIKUS sémájából (ami az SQLite-referencia forrása) előállítja
// ugyanannak a sémának a PostgreSQL-alakját, és kiírja a MIGRÁCIÓS fájlba. A kimenet ettől kezdve
// ARTEFAKTUM: számozott migráció, amit a merge után SOHA nem szerkesztünk (D-VS-3000 / 2. szabály);
// a javítás ÚJ migráció. Ez a szerszám tehát EGYSZER szül egy fájlt, nem futásidőben fordít.
//
// MIÉRT GENERÁLÁS, ÉS NEM KÉZZEL ÍRT MÁSODIK SÉMA. Mert két kézzel vezetett séma ELCSÚSZIK, és az
// elcsúszás némán történik (KUKA-018: egy fogalomnak egy otthona). A generálás a SZÁRMAZÁST köti
// össze; a FOLYAMATOS egyezést viszont nem ez tartja, hanem a `verify:pg-schema-parity` őr, ami a
// két alakot MINDKÉT irányban visszaméri. A generátor a születés, az őr a védelem.
//
// MIT NEM CSINÁL. Nem „fordítja le" a PostgreSQL-t SQLite-ra és fordítva sem (R146 §4 tiltása).
// A trigger-őrök VALÓDI plpgsql trigger-függvényként születnek (`RAISE EXCEPTION`), nem
// JS-emulációként és nem szöveg-cserével.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** A kanonikus séma szövege — EGY forrásból, a referencia-tárolóból. */
export function canonicalSchemaText() {
  const s = readFileSync(join(ROOT, 'v3ref/store.mjs'), 'utf8');
  const m = s.match(/^const SCHEMA = `([\s\S]*?)`;$/m);
  if (!m) throw new Error('v3_pg_schema_gen: a kanonikus SCHEMA nem található a v3ref/store.mjs-ben');
  return m[1];
}

/** A séma utasításokra bontása: a trigger-törzsek `BEGIN … END;`-je miatt nem elég a `;`. */
export function splitStatements(sql) {
  const out = [];
  let buf = '';
  let inTriggerBody = false;
  for (const line of sql.split('\n')) {
    const t = line.trim();
    if (/^CREATE TRIGGER/i.test(t)) inTriggerBody = true;
    buf += line + '\n';
    if (inTriggerBody) {
      if (/^END;/i.test(t)) { out.push(buf.trim()); buf = ''; inTriggerBody = false; }
      continue;
    }
    // A PONTOSVESSZŐ CSAK KÓD-SOR VÉGÉN ZÁR. MÉRT LELET: az `adjudication_authority_grant`
    // tábla törzsében áll egy MAGYARÁZÓ sor, ami pontosvesszővel végződik
    // („… a vetületből átvéve;"). A vak vágás ott KETTÉSZEDTE a táblát — a kimenet véletlenül
    // érvényes maradt (a `;` a kommentben a PostgreSQL-nek sem zár), de a besorolás és a
    // paritás-mérés már a FÉL táblát látta. Ez a KUKA-239 alakja: a hatókör nélküli minta a
    // szomszéd sort igazolja.
    if (!/^\s*--/.test(line) && /;\s*$/.test(t)) { if (buf.trim()) out.push(buf.trim()); buf = ''; }
  }
  if (buf.trim()) out.push(buf.trim());
  return out.filter((s) => s && !/^--/.test(s.split('\n').filter((l) => !/^\s*--/.test(l)).join('\n').trim() || '--'));
}

/** Oszlop-típusok: a jelentés marad, a NÉV a cél-illesztőé. */
function pgType(decl) {
  return decl
    // Az SQLite `INTEGER PRIMARY KEY AUTOINCREMENT` megfelelője a PostgreSQL identitás-oszlopa.
    // `BY DEFAULT` (nem `ALWAYS`), mert így a KIFEJEZETT azonosító-beszúrás is megmarad —
    // a referencia-battéria néhány programja él vele, és azt nem írjuk át (KUKA-121).
    .replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    // Az SQLite INTEGER-e 64 bites — a `bigint` ugyanaz a tartomány. (Az `integer` SZŰKÍTÉS volna.)
    .replace(/\bINTEGER\b/gi, 'bigint')
    .replace(/\bTEXT\b/gi, 'text');
}

/** `CREATE TABLE` → PostgreSQL alak. */
function convertTable(stmt) {
  return pgType(stmt);
}

/**
 * `CREATE TRIGGER` → VALÓDI plpgsql trigger-függvény + trigger.
 *
 * A két előforduló alak:
 *   (1) ŐR:        [WHEN <felt>] BEGIN SELECT RAISE(ABORT, '<üzenet>'); END;
 *   (2) TOVÁBBÍTÓ: BEGIN INSERT INTO … VALUES (NEW.…); END;
 *
 * A `WHEN` a PostgreSQL trigger `WHEN` záradékába NEM tehető át egy az egyben (ott alkérdés nem
 * állhat), ezért a feltétel a FÜGGVÉNY TÖRZSÉBE kerül `IF … THEN RAISE EXCEPTION`-ként. Ez nem
 * gyengítés: ugyanaz a feltétel, ugyanazon a soron, ugyanabban a pillanatban dől el.
 */
function convertTrigger(stmt) {
  const head = /^CREATE TRIGGER\s+(\w+)\s+(BEFORE|AFTER)\s+(INSERT|UPDATE|DELETE)\s+ON\s+(\w+)([\s\S]*?)\bBEGIN\b([\s\S]*?)\bEND;\s*$/i.exec(stmt);
  if (!head) throw new Error(`v3_pg_schema_gen: ismeretlen trigger-alak:\n${stmt.slice(0, 200)}`);
  const [, name, timing, event, table, whenPart, body] = head;

  const when = (whenPart || '').trim().replace(/^WHEN\s+/i, '').trim();
  const rowRef = event === 'DELETE' ? 'OLD' : 'NEW';

  const raise = /SELECT\s+RAISE\s*\(\s*ABORT\s*,\s*'([\s\S]*?)'\s*\)\s*;/i.exec(body);
  let inner;
  if (raise) {
    // Az üzenet SZÓ SZERINT megy át — a hívók egy része a SZÖVEGÉRE illeszt (pl. 'unknown_effect'),
    // tehát a mondat a szerződés része, nem dekoráció.
    const msg = raise[1].replace(/'/g, "''").replace(/%/g, '%%');
    inner = when
      ? `  IF ${when} THEN\n    RAISE EXCEPTION '${msg}';\n  END IF;`
      : `  RAISE EXCEPTION '${msg}';`;
  } else {
    const b = body.trim().replace(/;\s*$/, '');
    inner = when ? `  IF ${when} THEN\n    ${b};\n  END IF;` : `  ${b};`;
  }

  const ret = timing.toUpperCase() === 'BEFORE'
    ? (event === 'DELETE' ? 'OLD' : 'NEW')
    : 'NULL';

  return `CREATE FUNCTION ${name}_fn() RETURNS trigger AS $trg$
BEGIN
${inner}
  RETURN ${ret};
END;
$trg$ LANGUAGE plpgsql;

CREATE TRIGGER ${name} ${timing} ${event} ON ${table}
FOR EACH ROW EXECUTE FUNCTION ${name}_fn();`.replace(/\b(NEW|OLD)\./g, (mm) => mm);
}

/**
 * A BESOROLÁS A KÓD ELSŐ SORÁRA NÉZ, NEM A FÁJL ELSŐ KARAKTERÉRE. A kanonikus séma HOSSZÚ
 * indoklásokat ír az utasítások elé (ez a repó szokása, és érték) — az első alakom viszont
 * `^CREATE TRIGGER`-re illesztett, tehát a KOMMENTTEL BEVEZETETT triggereket nem ismerte fel, és
 * NÉMÁN átengedte őket SQLite-alakban. MÉRVE: 19 triggerből 11 konvertálódott, 8 nem — és a hiba
 * nem robbant, csak hibás SQL-t írt volna a migrációba (KUKA-239).
 */
function splitLead(stmt) {
  // CSAK a BEVEZETŐ komment-/üres sorokat választjuk le. A táblatörzsön BELÜLI kommentek a
  // kódhoz tartoznak és érintetlenül maradnak — az első alakom ezeket is levágta a besoroláshoz,
  // majd hossz-különbségből próbálta visszarakni a bevezetőt, ami elcsúszott (mérve: egy tábla
  // `AUTOINCREMENT`-je átkonvertálatlanul maradt a kimenetben).
  const lines = stmt.split('\n');
  let i = 0;
  while (i < lines.length && (/^\s*--/.test(lines[i]) || !lines[i].trim())) i++;
  return { lead: lines.slice(0, i).join('\n'), code: lines.slice(i).join('\n') };
}

export function generatePgSchema() {
  const stmts = splitStatements(canonicalSchemaText());
  const out = [];
  let tables = 0; let triggers = 0; let indexes = 0; let other = 0;
  for (const s of stmts) {
    const { lead, code } = splitLead(s);
    const pre = lead ? lead + '\n' : '';
    if (/^CREATE TABLE/i.test(code)) { out.push(pre + convertTable(code)); tables++; }
    else if (/^CREATE TRIGGER/i.test(code)) { out.push(pre + convertTrigger(code)); triggers++; }
    else if (/^CREATE (UNIQUE )?INDEX/i.test(code)) { out.push(pre + pgType(code)); indexes++; }
    else if (code.trim()) { out.push(pre + pgType(code)); other++; }
    else if (s.trim()) out.push(s);
  }
  // A SZÁMOK A KIMENETTEL EGYÜTT JÁRNAK: ha a besorolás megint elcsúszna, az a számon LÁTSZIK,
  // nem egy néma, rossz SQL-en (KUKA-049).
  generatePgSchema.counts = { tables, triggers, indexes, other };
  return out.join('\n\n');
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const target = process.argv[2];
  const body = generatePgSchema();
  if (!target) { process.stdout.write(body + '\n'); process.exit(0); }
  writeFileSync(resolve(ROOT, target), body + '\n');
  console.log(`kiírva: ${target} (${body.length} bájt)`);
}
